yarn:
  imagePullSecrets: []
  image:
    repository: crpi-wsxiy5y9ovijxdks.cn-hangzhou.personal.cr.aliyuncs.com/jockey/sealos
    tag: yarn-3.3.6
    pullPolicy: IfNotPresent
  paths:
    home: /opt/hadoop
    conf: /opt/hadoop/etc/hadoop
    dataRoot: /opt/hadoop/data
    logDir: /opt/hadoop/data/logs
    pidDir: /opt/hadoop/data/pids
    tmpDir: /opt/hadoop/data/tmp
  config:
    fsDefaultUri: file:///
    schedulerClass: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
    nodeManagerMemoryMb: 4096
    nodeManagerVCores: 2
    schedulerMinimumAllocationMb: 128
    schedulerMaximumAllocationMb: 4096
    logAggregationEnabled: false
    remoteAppLogDir: /tmp/logs
    extraCoreSiteProperties: []
    extraYarnSiteProperties: []
    extraMapredSiteProperties: []
  resourceManager:
    replicas: 1
    service:
      type: ClusterIP
      schedulerPort: 8030
      resourceTrackerPort: 8031
      clientPort: 8032
      adminPort: 8033
      webPort: 8088
    persistence:
      storageClass: openebs-hostpath
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
    probes:
      readiness:
        enabled: true
        path: /cluster
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 12
      liveness:
        enabled: true
        path: /cluster
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 6
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    extraEnv: []
  nodeManager:
    replicas: 1
    service:
      type: ClusterIP
      localizerPort: 8040
      nodeManagerPort: 8041
      webPort: 8042
    persistence:
      storageClass: openebs-hostpath
      accessModes:
        - ReadWriteOnce
      size: 20Gi
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
    probes:
      readiness:
        enabled: true
        path: /node
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 12
      liveness:
        enabled: true
        path: /node
        initialDelaySeconds: 60
        periodSeconds: 20
        timeoutSeconds: 5
        failureThreshold: 6
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    extraEnv: []

sealos:
  hostPrefix: yarn
  cloudDomain: 127.0.0.1.nip.io
  certSecretName: wildcard-cert
  ingressClassName: nginx
  ingress:
    enabled: true
  app:
    enabled: true
    icon: https://apache.org/logos/res/hadoop/default.png
    entryPath: /
