elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: "7.17.28"
    pullPolicy: IfNotPresent
  replicas: 3
  storage: 100Gi
  storageClass: "openebs-hostpath"
  requests:
    cpu: "1"
    memory: 4Gi
  limits:
    cpu: "2"
    memory: 8Gi
  javaHeap: 4g
  tlsSecretName: "elasticsearch-master-certs"
  password: "please-change-this-password"
  sysctl:
    resources:
      requests:
        cpu: 20m
        memory: 25Mi
      limits:
        cpu: 200m
        memory: 256Mi
