apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hdfs.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hdfs.configName" . | quote }}
    cloud.sealos.io/app-deploy-manager: {{ include "hdfs.configName" . | quote }}
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://{{ include "hdfs.nameNodeHost" . }}:{{ .Values.hdfs.nameNode.service.rpcPort }}</value>
      </property>
      <property>
        <name>hadoop.tmp.dir</name>
        <value>{{ .Values.hdfs.paths.tmpDir }}</value>
      </property>
{{- range .Values.hdfs.config.extraCoreSiteProperties }}
      <property>
        <name>{{ .name }}</name>
        <value>{{ .value }}</value>
      </property>
{{- end }}
    </configuration>
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <property>
        <name>dfs.replication</name>
        <value>{{ .Values.hdfs.config.dfsReplication }}</value>
      </property>
      <property>
        <name>dfs.permissions.enabled</name>
        <value>{{ .Values.hdfs.config.dfsPermissionsEnabled }}</value>
      </property>
      <property>
        <name>dfs.namenode.name.dir</name>
        <value>file://{{ .Values.hdfs.paths.dataRoot }}/name</value>
      </property>
      <property>
        <name>dfs.datanode.data.dir</name>
        <value>file://{{ .Values.hdfs.paths.dataRoot }}/data</value>
      </property>
      <property>
        <name>dfs.namenode.rpc-address</name>
        <value>{{ include "hdfs.nameNodeHost" . }}:{{ .Values.hdfs.nameNode.service.rpcPort }}</value>
      </property>
      <property>
        <name>dfs.namenode.http-address</name>
        <value>0.0.0.0:{{ .Values.hdfs.nameNode.service.httpPort }}</value>
      </property>
      <property>
        <name>dfs.datanode.address</name>
        <value>0.0.0.0:{{ .Values.hdfs.dataNode.service.dataPort }}</value>
      </property>
      <property>
        <name>dfs.datanode.ipc.address</name>
        <value>0.0.0.0:{{ .Values.hdfs.dataNode.service.ipcPort }}</value>
      </property>
      <property>
        <name>dfs.datanode.http.address</name>
        <value>0.0.0.0:{{ .Values.hdfs.dataNode.service.httpPort }}</value>
      </property>
{{- range .Values.hdfs.config.extraHdfsSiteProperties }}
      <property>
        <name>{{ .name }}</name>
        <value>{{ .value }}</value>
      </property>
{{- end }}
    </configuration>
  hadoop-env.sh: |
    export JAVA_HOME="${JAVA_HOME:-/opt/java}"
    export HADOOP_HOME="${HADOOP_HOME:-{{ .Values.hdfs.paths.home }}}"
    export HADOOP_CONF_DIR="${HADOOP_CONF_DIR:-{{ .Values.hdfs.paths.conf }}}"
    export HADOOP_LOG_DIR="${HADOOP_LOG_DIR:-{{ .Values.hdfs.paths.logDir }}}"
    export HADOOP_PID_DIR="${HADOOP_PID_DIR:-{{ .Values.hdfs.paths.pidDir }}}"
    export HADOOP_HEAPSIZE_MAX="${HADOOP_HEAPSIZE_MAX:-1024m}"
