apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.nameNodeName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hdfs.nameNodeName" . | quote }}
    cloud.sealos.io/app-deploy-manager: {{ include "hdfs.nameNodeName" . | quote }}
spec:
  type: {{ .Values.hdfs.nameNode.service.type }}
  selector:
    app: {{ include "hdfs.nameNodeName" . | quote }}
  ports:
    - name: rpc
      port: {{ .Values.hdfs.nameNode.service.rpcPort }}
      targetPort: rpc
    - name: http
      port: {{ .Values.hdfs.nameNode.service.httpPort }}
      targetPort: http
