apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.dataNodeName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hdfs.dataNodeName" . | quote }}
    cloud.sealos.io/app-deploy-manager: {{ include "hdfs.dataNodeName" . | quote }}
spec:
  type: {{ .Values.hdfs.dataNode.service.type }}
  selector:
    app: {{ include "hdfs.dataNodeName" . | quote }}
  ports:
    - name: data
      port: {{ .Values.hdfs.dataNode.service.dataPort }}
      targetPort: data
    - name: ipc
      port: {{ .Values.hdfs.dataNode.service.ipcPort }}
      targetPort: ipc
    - name: http
      port: {{ .Values.hdfs.dataNode.service.httpPort }}
      targetPort: http
