apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: hasura
spec:
  title: Hasura
  url: https://hasura.io
  gitRepo: https://github.com/hasura/graphql-engine
  author: hasura
  description: Hasura GraphQL Engine with PostgreSQL metadata storage and Data Connector
    Agent.
  readme: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/hasura/README.md
  icon: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/hasura/logo.png
  templateType: inline
  locale: en
  i18n:
    zh:
      description: hasura graphql engine 支持 postgresql metadata storage 与 data connector
        agent。
      readme: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/hasura/README_zh.md
  categories:
  - backend
  defaults:
    app_host:
      type: string
      value: hasura-${{ random(8) }}
    app_name:
      type: string
      value: hasura-${{ random(8) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${{ defaults.app_name }}-pg
subjects:
- kind: ServiceAccount
  name: ${{ defaults.app_name }}-pg
---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    kb.io/database: postgresql-16.4.0
    clusterdefinition.kubeblocks.io/name: postgresql
    clusterversion.kubeblocks.io/name: postgresql-16.4.0
spec:
  affinity:
    podAntiAffinity: Preferred
    tenancy: SharedNode
  clusterDefinitionRef: postgresql
  clusterVersionRef: postgresql-16.4.0
  terminationPolicy: Delete
  componentSpecs:
  - name: postgresql
    componentDefRef: postgresql
    disableExporter: true
    enabledLogs:
    - running
    replicas: 1
    serviceAccountName: ${{ defaults.app_name }}-pg
    switchPolicy:
      type: Noop
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 51Mi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: openebs-backup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: hasura/graphql-engine:v2.48.11
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: ${{ defaults.app_name }}
        image: hasura/graphql-engine:v2.48.11
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -ec
        args:
        - |
          export HASURA_GRAPHQL_METADATA_DATABASE_URL="postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/postgres"
          export PG_DATABASE_URL="${HASURA_GRAPHQL_METADATA_DATABASE_URL}"
          exec graphql-engine serve
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 25Mi
        ports:
        - containerPort: 8080
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: ${{ defaults.app_name }}-pg-conn-credential
              key: host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: ${{ defaults.app_name }}-pg-conn-credential
              key: port
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: ${{ defaults.app_name }}-pg-conn-credential
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: ${{ defaults.app_name }}-pg-conn-credential
              key: password
        - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ${{ defaults.app_name }}-pg-conn-credential
              key: endpoint
        - name: PG_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ${{ defaults.app_name }}-pg-conn-credential
              key: endpoint
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: 'true'
        - name: HASURA_GRAPHQL_DEV_MODE
          value: 'true'
        - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
          value: startup, http-log, webhook-log, websocket-log, query-log
        - name: HASURA_GRAPHQL_METADATA_DEFAULTS
          value: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://${{ defaults.app_name }}-data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://${{ defaults.app_name }}-data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://${{ defaults.app_name }}-data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://${{ defaults.app_name }}-data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://${{ defaults.app_name }}-data-connector-agent:8081/api/v1/snowflake"}}}}'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}-data-connector-agent
  annotations:
    originImageName: hasura/graphql-data-connector:v2.48.11
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-data-connector-agent
    app: ${{ defaults.app_name }}-data-connector-agent
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}-data-connector-agent
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}-data-connector-agent
    spec:
      automountServiceAccountToken: false
      containers:
      - name: ${{ defaults.app_name }}-data-connector-agent
        image: hasura/graphql-data-connector:v2.48.11
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 25Mi
        ports:
        - containerPort: 8081
        env:
        - name: QUARKUS_LOG_LEVEL
          value: ERROR
        - name: QUARKUS_OPENTELEMETRY_ENABLED
          value: 'false'
        livenessProbe:
          httpGet: &id001
            path: /api/v1/athena/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet: *id001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
        startupProbe:
          httpGet: *id001
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
  - name: tcp-8080
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ${{ defaults.app_name }}
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}-data-connector-agent
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-data-connector-agent
spec:
  ports:
  - name: tcp-8081
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: ${{ defaults.app_name }}-data-connector-agent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: 'client_header_buffer_size 64k;

      large_client_header_buffers 4 128k;'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: "if ($request_uri ~* \\.(js|css|gif|jpe?g|png))\
      \ {\n  expires 30d;\n  add_header Cache-Control \"public\";\n}"
spec:
  rules:
  - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ${{ defaults.app_name }}
            port:
              number: 8080
  tls:
  - hosts:
    - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
    secretName: ${{ SEALOS_CERT_SECRET_NAME }}
---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/hasura/logo.png
  name: Hasura
  type: link
