apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: AllinSSL
spec:
  title: 'AllinSSL'
  url: 'https://www.allinssl.com/'
  gitRepo: 'https://github.com/allinssl/allinssl'
  author: 'AllinSSL'
  description: 'AllinSSL 是一个集证书申请、管理、部署和监控于一体的SSL证书全生命周期管理工具。'
  readme: 'https://raw.githubusercontent.com/allinssl/allinssl/refs/heads/1.0.7/README.md'
  icon: 'https://allinssl.com/logo.svg'
  templateType: inline
  locale: zh
  categories:
    - dev-ops
  defaults:
    app_name:
      type: string
      value: allinssl-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
  inputs:
    ACCESS_URL:
      description: "Access URL"
      type: string
      default: "allinssl"
      required: true
    ALLINSSL_USER:
      description: "user"
      type: string
      default: "allinssl"
      required: true
    ALLINSSL_PWD:
      description: "password"
      type: string
      default: "allinssldocker"
      required: true

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: docker.1ms.run/allinssl/allinssl
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      containers:
      - name: ${{ defaults.app_name }}
        image: docker.1ms.run/allinssl/allinssl:latest
        env:
          - name: ALLINSSL_USER
            value: ${{ inputs.ALLINSSL_USER }}
          - name: ALLINSSL_PWD
            value: ${{ inputs.ALLINSSL_PWD }}
          - name: ALLINSSL_URL
            value: ${{ inputs.ACCESS_URL }}
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: vn-wwwvn-allinsslvn-data
          mountPath: /www/allinssl/data
        resources:
          requests:
            cpu: 50m
            memory: 51Mi
          limits:
            cpu: 500m
            memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /www/allinssl/data
          value: '1'
        name: vn-wwwvn-allinsslvn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8888
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8888
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}
---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://allinssl.com/logo.svg"
  name: "AllinSSL"
  type: link