apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: anki-sync-server
spec:
  title: 'anki-sync-server'
  url: 'https://docs.ankiweb.net/sync-server.html'
  gitRepo: 'https://github.com/yangchuansheng/anki-sync-server'
  author: 'Sealos'
  description: 'Self-Hosted Anki Sync Server'
  readme: 'https://raw.githubusercontent.com/yangchuansheng/anki-sync-server/main/README.md'
  icon: 'https://raw.githubusercontent.com/yangchuansheng/anki-sync-server/main/images/logo.jpeg'
  templateType: inline
  categories:
    - tool
  defaults:
    app_name:
      type: string
      value: anki-sync-server-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
  inputs:
    SYNC_USER1:
      description: 'the first user and password for Anki Sync Server，format: "user:pass"'
      type: string
      default: 'user:pass'
      required: false
    MAX_SYNC_PAYLOAD_MEGS:
      description: 'limit on uploads'
      type: string
      default: '100'
      required: false
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ghcr.io/yangchuansheng/anki-sync-server:24.06.3
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: ghcr.io/yangchuansheng/anki-sync-server:24.06.3
          env:
            - name: SYNC_USER1
              value: ${{ inputs.SYNC_USER1 }}
            - name: MAX_SYNC_PAYLOAD_MEGS
              value: ${{ inputs.MAX_SYNC_PAYLOAD_MEGS }}
            - name: SYNC_BASE
              value: /syncserver
          resources:
            requests:
              cpu: 10m
              memory: 6Mi
            limits:
              cpu: 100m
              memory: 64Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-syncserver
              mountPath: /syncserver
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /syncserver
          value: '1'
        name: vn-syncserver
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8080
  selector:
    app: ${{ defaults.app_name }}


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8080
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}