apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: btpanel
spec:
  title: '宝塔面板'
  url: 'https://www.bt.cn/'
  gitRepo: 'https://cnb.cool/btpanel/BaoTa'
  author: 'BTPanel'
  description: '宝塔面板是一个安全高效的服务器运维面板，一键配置：LAMP/LNMP、网站、数据库、FTP、SSL，通过Web端轻松管理服务器。'
  readme: 'https://raw.githubusercontent.com/aaPanel/BaoTa/refs/heads/docs/external/sealos.md'
  icon: 'https://www.bt.cn/static/new/images/logo_03.svg'
  templateType: inline
  locale: zh
  categories:
    - dev-ops
  defaults:
    app_name:
      type: string
      value: btpanel-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
  inputs:

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: btpanel/baota:nas
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      containers:
      - name: ${{ defaults.app_name }}
        image: btpanel/baota:nas
        env:
          - name: ADMIN_PATH
            value: '/'
        ports:
        - containerPort: 8888
        - containerPort: 80
        - containerPort: 443
        - containerPort: 3306
        - containerPort: 22
        - containerPort: 21
        volumeMounts:
        - name: vn-wwwvn
          mountPath: /www
        resources:
          requests:
            cpu: 200m
            memory: 204Mi
          limits:
            cpu: 2000m
            memory: 2048Mi
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /www
          value: '1'
        name: vn-wwwvn
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}-nodeport
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  selector:
    app: ${{ defaults.app_name }}
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  - name: ssh
    port: 22
    targetPort: 22
  - name: ftp
    port: 21
    targetPort: 21
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8888
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8888
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}
---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://www.bt.cn/static/new/images/logo_03.svg"
  name: "btpanel"
  type: link