apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: flowise
spec:
  title: 'Flowise'
  url: 'https://flowiseai.com/'
  gitRepo: 'https://github.com/FlowiseAI/Flowise'
  author: 'Sealos'
  description: '拖放 UI 组件来构建定制化的 LLM 应用。'
  readme: 'https://raw.githubusercontent.com/FlowiseAI/Flowise/main/README-ZH.md'
  icon: 'https://raw.githubusercontent.com/FlowiseAI/Flowise/main/packages/ui/public/favicon.ico'
  templateType: inline
  categories:
    - ai
  defaults:
    app_name:
      type: string
      value: flowise-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
  inputs:
    FLOWISE_USERNAME:
      description: 'username for flowise'
      type: string
      default: 'user'
      required: true
    FLOWISE_PASSWORD:
      description: 'password for flowise'
      type: string
      default: '1234'
      required: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: flowiseai/flowise:latest
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      containers:
        - name: ${{ defaults.app_name }}
          image: flowiseai/flowise:latest
          env:
            - name: PORT
              value: 80
            - name: FLOWISE_USERNAME
              value: ${{ inputs.FLOWISE_USERNAME }}
            - name: FLOWISE_PASSWORD
              value: ${{ inputs.FLOWISE_PASSWORD }}
            - name: DATABASE_PATH
              value: '/root/.flowise'
            - name: APIKEY_PATH
              value: '/root/.flowise'
            - name: SECRETKEY_PATH
              value: '/root/.flowise'
            - name: LOG_PATH
              value: '/root/.flowise'
          resources:
            requests:
              cpu: 50m
              memory: 51Mi
            limits:
              cpu: 500m
              memory: 512Mi
          command:
            - /bin/sh
            - '-c'
          args:
            - flowise start
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts: []
      volumes: []


---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 80
  selector:
    app: ${{ defaults.app_name }}


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 80
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}