apiVersion: template.app.sealos.io/v1beta1
kind: Template
metadata:
  name: llama2-chinese
spec:
  title: 'llama2-chinese'
  url: 'https://github.com/LinkSoul-AI/Chinese-Llama-2-7b'
  github: 'https://github.com/luanshaotong/text-generation-webui-docker.git'
  author: 'sealos'
  description: 'Fully open-source and commercially usable Chinese version of the Llama2 model, along with bilingual Chinese-English SFT dataset. Input format strictly adheres to the llama-2-chat format, ensuring compatibility and adaptation with all optimizations designed for the original llama-2-chat model.'
  readme: 'https://raw.githubusercontent.com/luanshaotong/text-generation-webui-docker/main/README.md'
  icon: 'https://github.com/LinkSoul-AI/Chinese-Llama-2-7b/blob/main/.github/preview.jpg'
  template_type: inline
  defaults:
    app_host:
      # number or string..
      type: string
      value: ${{ random(8) }}
    app_name:
      type: string
      value: llama-chinese-cpu-${{ random(8) }}
  inputs:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${{ defaults.app_name }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sealfs-csi-llama-chinese
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: luanshaotong/text-generation-webui-cpu:dev
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.run/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
    cloud.sealos.io/deploy-on-sealos: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  serviceName: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
        restartTime: '20230727190140'
    spec:
      containers:
        - name: ${{ defaults.app_name }}
          image: luanshaotong/text-generation-webui-cpu:dev
          env: 
          - name: "EXTRA_LAUNCH_ARGS"
            value: "--listen --verbose"
          command: ["sh", "-c"]
          args: ["cp /share/models/* /app/models && /scripts/docker-entrypoint.sh python3 /app/server.py --listen --verbose"]
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 8
              memory: 8G
          ports:
            - containerPort: 7860
          volumeMounts:
            - name: models
              mountPath: "/share/models"
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: llama-models
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/deploy-on-sealos: ${{ defaults.app_name }}
spec:
  ports:
    - port: 7860
  selector:
    app: ${{ defaults.app_name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
    cloud.sealos.io/deploy-on-sealos: ${{ defaults.app_name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 7860
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}