apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: lobe-chat
spec:
  title: 'Lobe Chat'
  url: 'https://github.com/lobehub/lobe-chat'
  gitRepo: 'https://github.com/lobehub/lobe-chat'
  author: 'Sealos'
  description: 'An open-source, modern-design ChatGPT/LLMs UI/Framework. Supports speech-synthesis, multi-modal, and extensible (function call) plugin system.'
  readme: 'https://raw.githubusercontent.com/lobehub/lobe-chat/main/README.zh-CN.md'
  icon: 'https://jsd.onmicrosoft.cn/npm/@lobehub/assets-logo@1.0.0/assets/logo-3d.webp'
  templateType: inline
  categories:
    - ai
  defaults:
    app_name:
      type: string
      value: lobe-chat-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
  inputs:
    OPENAI_API_KEY:
      description: 'This is the API key you apply on the OpenAI account page'
      type: string
      default: ''
      required: false
    OPENAI_PROXY_URL:
      description: 'If you manually configure the OpenAI interface proxy, you can use this configuration item to override the default OpenAI API request base URL'
      type: string
      default: 'https://api.openai.com/v1'
      required: false
    ACCESS_CODE:
      description: 'Add a password to access this service; you can set a long password to avoid leaking. If this value contains a comma, it is a password array.'
      type: string
      default: ''
      required: false
    OPENAI_MODEL_LIST:
      description: 'Used to control the model list. Use + to add a model, - to hide a model, and model_name=display_name to customize the display name of a model, separated by commas.'
      type: string
      default: ''
      required: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: lobehub/lobe-chat:v1.43.4
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: lobehub/lobe-chat:v1.43.4
          env:
            - name: OPENAI_API_KEY
              value: ${{ inputs.OPENAI_API_KEY }}
            - name: OPENAI_PROXY_URL
              value: ${{ inputs.OPENAI_PROXY_URL }}
            - name: ACCESS_CODE
              value: ${{ inputs.ACCESS_CODE }}
            - name: OPENAI_MODEL_LIST
              value: ${{ inputs.OPENAI_MODEL_LIST }}
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 512Mi
          command: []
          args: []
          ports:
            - containerPort: 3210
          imagePullPolicy: IfNotPresent
          volumeMounts: []
      volumes: []


---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 3210
  selector:
    app: ${{ defaults.app_name }}


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 3210
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}