apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: matrixgorilla
spec:
  title: '聚量猩球'
  url: 'https://www.matrixgorilla.com/'
  gitRepo: 'https://github.com/hello-stars/MatrixGorilla.git'
  author: 'Sealos'
  description: '多年服务500强企业体验管理经验沉淀，聚量猩球XM提供高效便捷的智能在线问卷系统、智能标签引擎及VR拟真实验能力，全面覆盖趋势洞察、概念验证、产品研发、产品试销、精益上市过程中的所有场景，让企业多快好省地获取消费者体验数据，降低企业生产投资决策风险，让每个研发决策反向赋能市场销售，实现口碑及业绩的双增长!'
  readme: 'https://raw.githubusercontent.com/hello-stars/MatrixGorilla/main/README.md'
  icon: 'https://diaoyan-files.automark.cc/logo/logo.png'
  templateType: inline
  locale: zh
  draft: true
  defaults:
    app_name:
      type: string
      value: matrixgorilla-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}-web
  annotations:
    originImageName: ${{ defaults.app_name }}-web
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-web
    app: ${{ defaults.app_name }}-web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}-web
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}-web
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}-web
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}-web
          image: >-
            registry.cn-beijing.aliyuncs.com/juliangxingqiu/sealos-java-web:latest
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          command: [ ]
          args: [ ]
          ports:
            - containerPort: 80
          imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}-api
  annotations:
    originImageName: ${{ defaults.app_name }}-api
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-api
    app: ${{ defaults.app_name }}-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}-api
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}-api
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}-api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ${{ defaults.app_name }}-api
          image: >-
            registry.cn-beijing.aliyuncs.com/juliangxingqiu/sealos-java-api:latest
          env:
            - name: ANSWER_URL
              value: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}/#/answer
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          command: [ ]
          args: [ ]
          ports:
            - containerPort: 15022
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}-web
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-web
spec:
  ports:
    - port: 80
  selector:
    app: ${{ defaults.app_name }}-web

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}-api
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-api
spec:
  ports:
    - port: 15022
  selector:
    app: ${{ defaults.app_name }}-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}-web
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-web
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_name }}-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1024m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 1024m
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}-web
                port:
                  number: 80
          - pathType: Prefix
            path: /api
            backend:
              service:
                name: ${{ defaults.app_name }}-api
                port:
                  number: 15022

  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: wildcard-cert