apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: mongo-express
spec:
  title: 'mongo-express'
  url: 'https://github.com/mongo-express/mongo-express'
  gitRepo: 'https://github.com/mongo-express/mongo-express'
  author: 'sealos'
  description: 'A web-based MongoDB admin interface written with Node.js, Express, and Bootstrap3'
  readme: 'https://raw.githubusercontent.com/mongo-express/mongo-express/master/README.md'
  icon: 'https://avatars.githubusercontent.com/u/17328297?s=48&v=4'
  templateType: inline
  defaults:
    app_name:
      type: string
      value: mongo-express-${{ random(8) }}
    app_host:
      type: string
      value: ${{ random(8) }}
  inputs:
    mongodb_conn_credential:
      description: 'mongodb conn credential, ex. mongodb://user:password@host:port/dbname'
      type: string
      default: ''
      required: true
    custom_express_user:
      description: 'User-defined mongo express login account user (non-database). The default is `admin`.'
      type: string
      default: 'admin'
      required: false
    custom_express_password:
        description: 'User-defined mongo express login account password (non-database). The default is `sealos`.'
        type: string
        default: 'sealos'
        required: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: mongo-express
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_URL
              value: ${{ inputs.mongodb_conn_credential }}
            - name: ME_CONFIG_BASICAUTH
              value: 'true'
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: ${{ inputs.custom_express_user }}
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: ${{ inputs.custom_express_password }}
            - name: ME_CONFIG_OPTIONS_EDITORTHEME
              value: ambiance
          resources:
            requests:
              cpu: 50m
              memory: 51Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
          volumeMounts: []
      volumes: []
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8081
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8081
  selector:
    app: ${{ defaults.app_name }}