apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: oneStepShortcuts
spec:
  title: '桌面快捷方式'
  author: '白夜'
  description: '一键新建桌面快捷方式，运行本应用不会产生费用'
  url: 'https://github.com/nightwhite/own-sealos-templates'
  gitRepo: 'https://github.com/nightwhite/own-sealos-templates'
  icon: 'https://oss.laf.run/j4vo9u-ico/logo.png'
  readme: 'https://raw.githubusercontent.com/nightwhite/own-sealos-templates/main/oneStepShortcuts/README.md'
  templateType: inline
  defaults:
    app_name:
      type: string
      value: shortcuts-${{ random(8) }}
  inputs:
    app_name:
      description: '快捷方式显示的名称'
      type: string
      default: ''
      required: true
    app_url:
      description: '快捷方式需要打开的链接'
      type: string
      default: ''
      required: true
    app_icon:
      description: '快捷方式图标 URL 地址'
      type: string
      default: ''

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: ${{ inputs.app_url }}
  displayType: normal
  icon: ${{ inputs.app_icon }}
  menuData:
    nameColor: text-black
  name: ${{ inputs.app_name }}
  type: iframe
