apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: open-webui
spec:
  title: 'Open WebUI'
  url: 'https://github.com/open-webui/open-webui'
  gitRepo: 'https://github.com/open-webui/open-webui'
  author: 'Sealos'
  description: 'User-friendly WebUI for LLMs (Formerly Ollama WebUI)'
  readme: 'https://raw.githubusercontent.com/open-webui/open-webui/main/README.md'
  icon: 'https://avatars.githubusercontent.com/u/158137808?s=48&v=4'
  templateType: inline
  categories:
    - ai
  defaults:
    app_host:
      type: string
      value: ${{ random(8) }}
    app_name:
      type: string
      value: open-webui-${{ random(8) }}
  inputs:

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ghcr.io/open-webui/open-webui:v0.5.4
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      initContainers:
        - name: init-data
          image: ghcr.io/open-webui/open-webui:v0.5.4
          command: ["/bin/bash", "-c", "if [ ! -f /data/config.json ]; then echo 'Cloning data folder'; cp -Rv /app/backend/data/* /data/; echo 'Done'; else echo 'Data folder already exists'; fi"]
          volumeMounts:
            - name: vn-data
              mountPath: "/data"
        - name: copy-data
          image: ghcr.io/open-webui/open-webui:v0.5.4
          command: ["/bin/bash", "-c", "if [ ! -f /app/backend/data/config.json ]; then echo 'Coping data folder'; cp -Rv /data/* /app/backend/data/; echo 'Done'; else echo 'Backend data folder already exists'; fi"]
          volumeMounts:
            - name: vn-data
              mountPath: "/data"
            - name: vn-appvn-backendvn-data
              mountPath: /app/backend/data
      containers:
        - name: ${{ defaults.app_name }}
          image: ghcr.io/open-webui/open-webui:v0.5.4
          env:
            - name: OLLAMA_BASE_URL
              value: ''
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          command: []
          args: []
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-appvn-backendvn-data
              mountPath: /app/backend/data
      volumes: []
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /app/backend/data
          value: '1'
        name: vn-appvn-backendvn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /data
          value: '1'
        name: vn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8080
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8080
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://avatars.githubusercontent.com/u/30179644?s=48&v=4"
  name: "Open WebUI"
  type: link
