apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: rustfs
spec:
  title: 'RustFS'
  url: 'https://rustfs.coms'
  gitRepo: 'https://github.com/rustfs/rustfs'
  author: 'Sealos'
  description: '🚀 High-performance distributed object storage for MinIO alternative.'
  readme: 'https://raw.githubusercontent.com/rustfs/rustfs/master/README.md'
  icon: 'https://avatars.githubusercontent.com/u/151849438?s=48&v=4'
  templateType: inline
  categories:
    - storage
  defaults:
    app_host:
      # number or string.
      type: string
      value: ${{ random(8) }}
    app_name:
      type: string
      value: rustfs-${{ random(8) }}
  inputs:
    accesskey:
      description: 'RustFS Console Username (must be at least length 8)'
      type: string
      default: ''
      required: true
    secretkey:
      description: 'RustFS Console Password (must be at least length 8)'
      type: string
      default: ''
      required: true
    storage:
      description: 'Storage size for each server in Gi (4 servers in total)'
      type: number
      default: ''
      required: true
    important note:
      description: 'Changing storage size of Rustfs leads to unrecoverable crashes.'
      type: string
      default: ''
      required: false
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: rustfs/rustfs
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    app: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  replicas: 1
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: rustfs/rustfs:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUSTFS_ACCESS_KEY
              value: ${{ inputs.accesskey }}
            - name: RUSTFS_SECRET_KEY
              value: ${{ inputs.secretkey }}
            - name: RUSTFS_VOLUMES
              value: /data/
            - name: RUSTFS_CONSOLE_ENABLE
              value: 'true'
            - name: RUSTFS_ADDRESS
              value: ':9000'
            - name: RUSTFS_OBS_LOG_DIRECTORY
              value: /var/logs/rustfs
          ports:
            - name: rustfs
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /data
          value: ' ${{  inputs.storage }} '
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: ${{  inputs.storage }}Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  selector:
    app: ${{ defaults.app_name }}
  clusterIP: None
  ports:
    - name: rustfs
      port: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 9000
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}