apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: umami
spec:
  title: 'Umami Analytics'
  url: 'https://umami.is/docs'
  gitRepo: 'https://github.com/umami-software/umami'
  author: 'umami-software'
  description: '🔥 Umami 是一个简单、快速、注重隐私的 Google Analytics 替代品。支持多种数据库,包括 PostgreSQL、MySQL 和 MariaDB。'
  readme: 'https://raw.githubusercontent.com/umami-software/umami/master/README.md'
  icon: 'https://raw.githubusercontent.com/umami-software/umami/master/public/favicon.ico'
  templateType: inline
  categories:
    - analytics
  defaults:
    app_host:
      type: string
      value: umami-${{ random(8) }}
    app_name:
      type: string
      value: umami-${{ random(8) }}
  inputs:
    DATABASE_URL:
      description: "数据库连接URL (例如: postgresql://user:pass@host:5432/dbname)"
      type: string
      required: true
    DATABASE_TYPE:
      description: "数据库类型 (postgresql 或 mysql)"
      type: string
      required: true
    APP_SECRET:
      description: "应用密钥，用于会话加密"
      type: string
      required: true
      default: ${{ random(32) }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: docker.umami.is/umami-software/umami:postgresql-latest
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      containers:
        - name: ${{ defaults.app_name }}
          image: docker.umami.is/umami-software/umami:postgresql-latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: ${{ inputs.DATABASE_URL }}
            - name: DATABASE_TYPE
              value: ${{ inputs.DATABASE_TYPE }}
            - name: APP_SECRET
              value: ${{ inputs.APP_SECRET }}

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 3000
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://raw.githubusercontent.com/umami-software/umami/master/public/favicon.ico"
  name: ${{ defaults.app_name }}
  type: iframe