apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: nakama
spec:
  title: 'Nakama Server'
  url: 'https://heroiclabs.com/nakama/'
  gitRepo: 'https://github.com/heroiclabs/nakama'
  author: 'Sealos'
  description: 'Nakama is an open-source game server for real-time multiplayer, social features, and live ops.'
  readme: 'https://raw.githubusercontent.com/labring-actions/templates/main/template/nakama/README.md'
  icon: 'https://raw.githubusercontent.com/labring-actions/templates/main/template/nakama/logo.svg'
  templateType: inline
  locale: en
  i18n:
    zh:
      title: 'Nakama 游戏服务器'
      description: 'Nakama 是一个开源的游戏开发平台，能自动处理用户登录、实时聊天、排行榜、成就系统，还能智能匹配玩家。'
  categories:
    - game
    - backend
  defaults:
    app_name:
      type: string
      value: nakama-${{ random(8) }}
    app_host:
      type: string
      value: nakama-${{ random(8) }}
    http_host:
      type: string
      value: nakama-http-${{ random(8) }}
    grpc_host:
      type: string
      value: nakama-grpc-${{ random(8) }}
    console_grpc_host:
      type: string
      value: nakama-console-grpc-${{ random(8) }}
    console_username:
      type: string
      value: admin
    console_password:
      type: string
      value: ${{ random(16) }}
    session_encryption_key:
      type: string
      value: ${{ random(32) }}
    session_refresh_encryption_key:
      type: string
      value: ${{ random(32) }}
    runtime_http_key:
      type: string
      value: ${{ random(32) }}
    console_signing_key:
      type: string
      value: ${{ random(32) }}
    console_mfa_storage_encryption_key:
      type: string
      value: ${{ random(32) }}
    server_key:
      type: string
      value: ${{ random(32) }}

  inputs:
    enable_grpc:
      description: 'Expose gRPC ports 7348/7349 publicly'
      type: boolean
      default: 'false'
      required: false
    console_username:
      description: 'Nakama Console admin username (overrides the default)'
      type: string
      default: 'admin'
      required: true
    console_password:
      description: 'Nakama Console admin password (set for initial login)'
      type: string
      default: ''
      required: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${{ defaults.app_name }}-pg
subjects:
  - kind: ServiceAccount
    name: ${{ defaults.app_name }}-pg

---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  labels:
    kb.io/database: postgresql-16.4.0
    clusterdefinition.kubeblocks.io/name: postgresql
    clusterversion.kubeblocks.io/name: postgresql-16.4.0
  name: ${{ defaults.app_name }}-pg
  namespace: ns-admin
spec:
  affinity:
    podAntiAffinity: Preferred
    tenancy: SharedNode
  clusterDefinitionRef: postgresql
  clusterVersionRef: postgresql-16.4.0
  componentSpecs:
    - componentDefRef: postgresql
      disableExporter: true
      enabledLogs:
        - running
      name: postgresql
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 51Mi
      serviceAccountName: ${{ defaults.app_name }}-pg
      switchPolicy:
        type: Noop
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
              storageClassName: openebs-backup
  terminationPolicy: Delete

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${{ defaults.app_name }}-pg-init
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
spec:
  completions: 1
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: pgsql-init
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: host
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: port
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: password
            - name: DB_NAME
              value: nakama
          command:
            - /bin/sh
            - -c
            - |
              until psql "postgresql://${PG_USERNAME}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/postgres" -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" | grep -q 1; do
                psql "postgresql://${PG_USERNAME}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/postgres" -c "CREATE DATABASE ${DB_NAME};" || true
                sleep 2
              done
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 300

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: heroiclabs/nakama:3.35.1
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: init-modules-dir
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-data
              mountPath: /data
          args:
            - sh
            - -lc
            - mkdir -p /data/modules
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
        - name: wait-for-postgres
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: host
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: port
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: password
            - name: DB_NAME
              value: nakama
          command:
            - /bin/sh
            - -c
            - |
              echo "waiting for postgresql to be ready..."
              until pg_isready -h ${PG_HOST} -p ${PG_PORT} -U ${PG_USERNAME}; do
                echo "postgresql not ready, rechecking in 2s"
                sleep 2
              done
              echo "postgresql is ready"
              until psql -h ${PG_HOST} -p ${PG_PORT} -U ${PG_USERNAME} -d postgres \
                -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}';" | grep -q 1; do
                echo "database ${DB_NAME} not found, rechecking in 2s"
                sleep 2
              done
              echo "database ${DB_NAME} exists"
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        - name: migrate
          image: heroiclabs/nakama:3.35.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-data
              mountPath: /data
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: host
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: port
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: password
            - name: NAKAMA_DATABASE_ADDRESS
              value: >-
                $(PG_USERNAME):$(PG_PASSWORD)@$(PG_HOST):$(PG_PORT)/nakama?sslmode=disable
          args:
            - migrate
            - up
            - --database.address
            - $(NAKAMA_DATABASE_ADDRESS)
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      containers:
        - name: ${{ defaults.app_name }}
          image: heroiclabs/nakama:3.35.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: host
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: port
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: password
            - name: NAKAMA_DATABASE_ADDRESS
              value: >-
                $(PG_USERNAME):$(PG_PASSWORD)@$(PG_HOST):$(PG_PORT)/nakama?sslmode=disable
            - name: NAKAMA_SESSION_ENCRYPTION_KEY
              value: ${{ defaults.session_encryption_key }}
            - name: NAKAMA_SESSION_REFRESH_ENCRYPTION_KEY
              value: ${{ defaults.session_refresh_encryption_key }}
            - name: NAKAMA_RUNTIME_HTTP_KEY
              value: ${{ defaults.runtime_http_key }}
            - name: NAKAMA_CONSOLE_SIGNING_KEY
              value: ${{ defaults.console_signing_key }}
            - name: NAKAMA_CONSOLE_MFA_STORAGE_ENCRYPTION_KEY
              value: ${{ defaults.console_mfa_storage_encryption_key }}
            - name: NAKAMA_CONSOLE_USERNAME
              value: ${{ inputs.console_username }}
            - name: NAKAMA_CONSOLE_PASSWORD
              value: ${{ inputs.console_password }}
            - name: NAKAMA_SOCKET_SERVER_KEY
              value: ${{ defaults.server_key }}
          ports:
            - name: console-grpc
              containerPort: 7348
            - name: grpc
              containerPort: 7349
            - name: http
              containerPort: 7350
            - name: metrics
              containerPort: 7351
          args:
            - --name
            - ${{ defaults.app_name }}
            - --database.address
            - $(NAKAMA_DATABASE_ADDRESS)
            - --logger.level
            - INFO
            - --session.encryption_key
            - $(NAKAMA_SESSION_ENCRYPTION_KEY)
            - --session.refresh_encryption_key
            - $(NAKAMA_SESSION_REFRESH_ENCRYPTION_KEY)
            - --runtime.http_key
            - $(NAKAMA_RUNTIME_HTTP_KEY)
            - --console.signing_key
            - $(NAKAMA_CONSOLE_SIGNING_KEY)
            - --console.mfa.storage_encryption_key
            - $(NAKAMA_CONSOLE_MFA_STORAGE_ENCRYPTION_KEY)
            - --console.username
            - $(NAKAMA_CONSOLE_USERNAME)
            - --console.password
            - $(NAKAMA_CONSOLE_PASSWORD)
            - --socket.server_key
            - $(NAKAMA_SOCKET_SERVER_KEY)
            - --runtime.path
            - /data/modules
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /data
          value: '0.1'
        name: vn-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  type: ClusterIP
  selector:
    app: ${{ defaults.app_name }}
  ports:
    - name: console-grpc
      port: 7348
      targetPort: 7348
    - name: grpc
      port: 7349
      targetPort: 7349
    - name: http
      port: 7350
      targetPort: 7350
    - name: metrics
      port: 7351
      targetPort: 7351

---
${{ if(inputs.enable_grpc) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}-grpc
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.grpc_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
spec:
  rules:
    - host: ${{ defaults.grpc_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 7349
  tls:
    - hosts:
        - ${{ defaults.grpc_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}
${{ endif() }}

---
${{ if(inputs.enable_grpc) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}-console-grpc
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.console_grpc_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
spec:
  rules:
    - host: ${{ defaults.console_grpc_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 7348
  tls:
    - hosts:
        - ${{ defaults.console_grpc_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}
${{ endif() }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}-http
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.http_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.http_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 7350
  tls:
    - hosts:
        - ${{ defaults.http_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 7351
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: 'https://raw.githubusercontent.com/labring-actions/templates/main/template/nakama/logo.svg'
  name: 'Nakama Server'
  type: link