apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: pdf2zh
spec:
  title: 'PDFMathTranslate'
  url: 'https://pdf2zh.com/'
  gitRepo: 'https://github.com/Byaidu/PDFMathTranslate'
  author: 'Sealos'
  description: 'PDFMathTranslate is an open-source PDF scientific paper translation with preserved formats.'
  readme: 'https://raw.githubusercontent.com/Byaidu/PDFMathTranslate/refs/heads/main/README.md'
  icon: 'https://raw.githubusercontent.com/Byaidu/PDFMathTranslate/main/docs/images/banner.png'
  templateType: inline
  locale: en
  i18n:
    zh:
      description: '基于 AI 完整保留排版的 PDF 文档全文双语翻译，支持 Google/DeepL/Ollama/OpenAI 等服务。'
      readme: 'https://raw.githubusercontent.com/Byaidu/PDFMathTranslate/refs/heads/main/docs/README_zh-CN.md'
  categories:
    - tool
    - ai
  defaults:
    app_host:
      # number or string..
      type: string
      value: pdf2zh-${{ random(8) }}
    app_name:
      type: string
      value: pdf2zh-${{ random(8) }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: byaidu/pdf2zh:1.9.6
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: byaidu/pdf2zh:1.9.6
          resources:
            requests:
              cpu: 20m
              memory: 204Mi
            limits:
              cpu: 200m
              memory: 2048Mi
          ports:
            - containerPort: 7860
          imagePullPolicy: IfNotPresent


---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 7860
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 7860
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://raw.githubusercontent.com/Byaidu/PDFMathTranslate/main/docs/images/banner.png"
  name: "PDFMathTranslate"
  type: link