apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: palworld-export
spec:
  title: '帕鲁存档导出器'
  url: 'https://github.com/yangchuansheng/templates-palworld'
  gitRepo: 'https://github.com/yangchuansheng/templates-palworld'
  author: 'Sealos'
  description: '通过图形化界面导出幻兽帕鲁 / PalWorld 存档数据'
  readme: 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/yangchuansheng/templates-palworld/main/template/palworld-export/README.md'
  icon: 'https://raw.githubusercontent.com/yangchuansheng/templates-palworld/main/template/palworld-export/logo.jpg'
  templateType: inline
  categories:
    - game
  defaults:
    app_name:
      type: string
      value: palworld-export-${{ random(8) }}
    app_host:
      type: string
      value: palworld-export-${{ random(8) }}
  inputs:
    APP_NAME:
      description: "帕鲁私服应用名称"
      type: string
      default: ""
      required: true

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: hurlenko/filebrowser
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: sync-data-dir
          image: bitnami/kubectl
          command:
            - bash
            - -c
          args:
            - mkdir -p /data/Pal/Saved &&kubectl cp ${{ inputs.APP_NAME }}-0:/palworld/Pal/Saved /data/Pal/Saved -c ${{ inputs.APP_NAME }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-palworld
              mountPath: /data
      containers:
        - name: ${{ defaults.app_name }}
          image: hurlenko/filebrowser
          resources:
            requests:
              cpu: 50m
              memory: 12Mi
            limits:
              cpu: 500m
              memory: 128Mi
          ports:
            - containerPort: 8080
              name: filebrowser
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-palworld
              mountPath: /data
            - name: vn-config
              mountPath: /config
      securityContext:
        runAsUser: 0
      serviceAccountName: ${{ SEALOS_SERVICE_ACCOUNT }}
      serviceAccount:  ${{ SEALOS_SERVICE_ACCOUNT }}
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /data
          value: '10'
        name: vn-palworld
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    - metadata:
        annotations:
          path: /config
          value: '1'
        name: vn-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1g
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8080
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}