apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: share-storage
spec:
  title: '共享存储'
  url: 'https://github.com/labring-sigs/templates'
  gitRepo: 'https://github.com/labring-sigs/templates'
  author: 'Sealos'
  description: 'Any share storage'
  readme: 'https://raw.githubusercontent.com/labring-sigs/templates/main/template/share-storage/README.md'
  icon: 'https://raw.githubusercontent.com/labring-sigs/templates/main/template/share-storage/nfs.png'
  templateType: inline
  categories:
    - storage
  defaults:
    app_name:
      type: string
      value: share-storage-${{ random(8) }}
  inputs:
    SHARE_STORAGE_SIZE:
      description: 'share storage size'
      type: number
      default: '1'
      required: true
    STORAGE_CLASS:
      description: 'storage class name'
      type: string
      default: 'nfs-csi'
      required: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${{ defaults.app_name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${{ inputs.SHARE_STORAGE_SIZE }}Gi
  storageClassName: ${{ inputs.STORAGE_CLASS }}