{{- if .Values.sealos.app.enabled }}
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: skywalking
  namespace: {{ .Release.Namespace }}
  labels:
    app: "skywalking"
spec:
  data:
    url: https://{{ .Values.sealos.hostPrefix }}.{{ .Values.sealos.cloudDomain }}{{ .Values.sealos.app.entryPath }}
  displayType: normal
  icon: {{ .Values.sealos.app.icon | quote }}
  name: "SkyWalking"
  type: link
{{- end }}
