apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skywalking-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: "skywalking"
    component: "ui"
    cloud.sealos.io/app-deploy-manager-domain: {{ .Values.sealos.hostPrefix | quote }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.sealos.ingressClassName | quote }}
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
{{- if .Values.sealos.ingressClassName }}
  ingressClassName: {{ .Values.sealos.ingressClassName | quote }}
{{- end }}
  tls:
    - hosts:
        - {{ .Values.sealos.hostPrefix }}.{{ .Values.sealos.cloudDomain }}
      secretName: {{ .Values.sealos.certSecretName }}
  rules:
    - host: {{ .Values.sealos.hostPrefix }}.{{ .Values.sealos.cloudDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skywalking-ui
                port:
                  number: {{ .Values.skywalking.ui.service.port }}
