{{- if and .Values.skywalking.banyandb.enabled .Values.skywalking.banyandb.persistence.enabled (not .Values.skywalking.banyandb.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skywalking-banyandb-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: "skywalking"
    component: "banyandb"
spec:
{{- if .Values.skywalking.banyandb.persistence.storageClass }}
  storageClassName: {{ .Values.skywalking.banyandb.persistence.storageClass | quote }}
{{- end }}
  accessModes:
{{ toYaml .Values.skywalking.banyandb.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.skywalking.banyandb.persistence.size | quote }}
{{- end }}
