apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap
  namespace: {{ .Release.Namespace }}
  labels:
    app: "skywalking"
    component: "oap"
spec:
  type: {{ .Values.skywalking.oap.service.type }}
  selector:
    app: "skywalking"
    component: "oap"
  ports:
    - name: grpc
      port: {{ .Values.skywalking.oap.service.grpcPort }}
      targetPort: grpc
    - name: http
      port: {{ .Values.skywalking.oap.service.httpPort }}
      targetPort: http
    - name: zipkin
      port: {{ .Values.skywalking.oap.service.zipkinPort }}
      targetPort: zipkin
