{{- if .Values.skywalking.banyandb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: skywalking-banyandb
  namespace: {{ .Release.Namespace }}
  labels:
    app: "skywalking"
    component: "banyandb"
spec:
  type: {{ .Values.skywalking.banyandb.service.type }}
  selector:
    app: "skywalking"
    component: "banyandb"
  ports:
    - name: grpc
      port: {{ .Values.skywalking.banyandb.service.grpcPort }}
      targetPort: grpc
    - name: http
      port: {{ .Values.skywalking.banyandb.service.httpPort }}
      targetPort: http
{{- end }}
