apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: "skywalking"
    component: "ui"
spec:
  type: {{ .Values.skywalking.ui.service.type }}
  selector:
    app: "skywalking"
    component: "ui"
  ports:
    - name: http
      port: {{ .Values.skywalking.ui.service.port }}
      targetPort: http
