apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: {{ .Release.Namespace }}
  labels:
    app: "logstash"
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
    pipeline.ordered: auto
    config.reload.automatic: false
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
    }

    output {
      elasticsearch {
        hosts => ["https://elasticsearch-master.{{ .Release.Namespace }}.svc:9200"]
        user => "elastic"
        password => "${ELASTICSEARCH_PASSWORD}"
        ssl => true
        cacert => "/usr/share/logstash/config/certs/tls.crt"
        index => "logstash-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
