apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: {{ .Release.Namespace }}
  labels:
    app: "logstash"
spec:
  replicas: {{ .Values.logstash.replicas }}
  selector:
    matchLabels:
      app: "logstash"
  template:
    metadata:
      labels:
        app: "logstash"
    spec:
      containers:
        - name: logstash
          image: "{{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}"
          imagePullPolicy: "{{ .Values.logstash.image.pullPolicy }}"
          ports:
            - name: beats
              containerPort: 5044
            - name: api
              containerPort: 9600
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms{{ .Values.logstash.javaHeap }} -Xmx{{ .Values.logstash.javaHeap }}"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-master-credentials
                  key: password
          readinessProbe:
            tcpSocket:
              port: 5044
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 5044
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.logstash.requests.cpu | quote }}
              memory: {{ .Values.logstash.requests.memory | quote }}
            limits:
              cpu: {{ .Values.logstash.limits.cpu | quote }}
              memory: {{ .Values.logstash.limits.memory | quote }}
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
              readOnly: true
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
              readOnly: true
            - name: elasticsearch-ca
              mountPath: /usr/share/logstash/config/certs
              readOnly: true
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline
        - name: elasticsearch-ca
          secret:
            secretName: {{ .Values.elasticsearch.caSecretName }}
