apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: {{ .Release.Namespace }}
  labels:
    app: "logstash"
spec:
  type: ClusterIP
  selector:
    app: "logstash"
  ports:
    - name: beats
      protocol: TCP
      port: 5044
      targetPort: 5044
    - name: api
      protocol: TCP
      port: 9600
      targetPort: 9600
