apiVersion: v2
name: skywalking
description: Apache SkyWalking helm chart for Sealos cluster image
version: 0.1.0
appVersion: "10.4.0"
type: application
icon: https://skywalking.apache.org/images/project/skywalking.svg
