apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: changedetection
spec:
  title: "Change Detection"
  url: "https://changedetection.io/"
  gitRepo: "https://github.com/dgtlmoon/changedetection.io"
  author: "Sealos"
  description: "Self-hosted free open source website change detection, monitor and notification service. Get instant notifications when websites change."
  readme: "https://raw.githubusercontent.com/dgtlmoon/changedetection.io/master/README.md"
  icon: "https://changedetection.io/themes/cdio/assets/images/favicons/apple-touch-icon.png"
  templateType: inline
  locale: en
  i18n:
    zh:
      description: "自托管的免费开源网页变更检测、监控和通知服务。当网站发生变化时获得即时通知。"
  categories:
    - tool
    - monitor
  defaults:
    app_host:
      type: string
      value: changedetection-${{ random(8) }}
    app_name:
      type: string
      value: changedetection-${{ random(8) }}
  inputs:
    fetch_workers:
      description: "Number of parallel/concurrent fetchers (default: 10)"
      type: string
      default: "10"
      required: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ghcr.io/dgtlmoon/changedetection.io:0.50.43
    deploy.cloud.sealos.io/minReplicas: "1"
    deploy.cloud.sealos.io/maxReplicas: "1"
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: ghcr.io/dgtlmoon/changedetection.io:0.50.43
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5000"
            - name: BASE_URL
              value: "https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}"
            - name: FETCH_WORKERS
              value: ${{ inputs.fetch_workers }}
            - name: USE_X_SETTINGS
              value: "1"
            - name: HIDE_REFERER
              value: "true"
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 12Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: vn-datastore
              mountPath: /datastore
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /datastore
          value: "1"
        name: vn-datastore
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 5000
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://changedetection.io/themes/cdio/assets/images/favicons/apple-touch-icon.png"
  name: "Change Detection"
  type: link
