apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: pangolin
spec:
  title: Pangolin
  url: https://pangolin.net
  gitRepo: https://github.com/fosrl/pangolin
  author: FOSRL
  description: Open-source identity-based remote access platform built on WireGuard.
  readme: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/pangolin/README.md
  icon: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/pangolin/logo.png
  templateType: inline
  locale: en
  i18n:
    zh:
      description: 基于 WireGuard 的开源身份访问与远程连接平台，提供零信任访问控制能力。
      readme: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/pangolin/README_zh.md
  categories:
  - backend
  defaults:
    app_host:
      type: string
      value: pangolin-${{ random(8) }}
    app_name:
      type: string
      value: pangolin-${{ random(8) }}
    server_secret:
      type: string
      value: ${{ random(32) }}
  inputs:
    gerbil_base_endpoint:
      description: Public endpoint advertised by Gerbil to Pangolin.
      type: string
      default: pangolin.example.com
      required: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ defaults.app_name }}-config
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-config
data:
  config.yml: |
    gerbil:
      start_port: 51820
      base_endpoint: "${{ inputs.gerbil_base_endpoint }}"

    app:
      dashboard_url: "https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}"
      log_level: "info"
      telemetry:
        anonymous_usage: true

    domains:
      domain1:
        base_domain: "${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}"

    server:
      secret: "${{ defaults.server_secret }}"
      cors:
        origins:
        - "https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}"
        methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "PATCH"
        allowed_headers:
        - "X-CSRF-Token"
        - "Content-Type"
        credentials: false

    flags:
      require_email_verification: false
      disable_signup_without_invite: true
      disable_user_create_org: false
      allow_raw_resources: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${{ defaults.app_name }}-config
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}-pangolin
  annotations:
    originImageName: docker.io/fosrl/pangolin:1.15.2
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-pangolin
    app: ${{ defaults.app_name }}-pangolin
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}-pangolin
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}-pangolin
    spec:
      automountServiceAccountToken: false
      containers:
      - name: ${{ defaults.app_name }}-pangolin
        image: docker.io/fosrl/pangolin:1.15.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 102Mi
        ports:
        - containerPort: 3000
          protocol: TCP
        - containerPort: 3001
          protocol: TCP
        - containerPort: 3002
          protocol: TCP
        - containerPort: 3003
          protocol: TCP
        volumeMounts:
        - name: shared-config
          mountPath: /app/config
        - name: pangolin-config
          mountPath: /app/config/config.yml
          subPath: config.yml
        livenessProbe:
          httpGet: &pangolin_health
            path: /api/v1/
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 15
        readinessProbe:
          httpGet: *pangolin_health
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 15
        startupProbe:
          httpGet: *pangolin_health
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 60
      volumes:
      - name: shared-config
        persistentVolumeClaim:
          claimName: ${{ defaults.app_name }}-config
      - name: pangolin-config
        configMap:
          name: ${{ defaults.app_name }}-config
          items:
          - key: config.yml
            path: config.yml
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}-pangolin
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-pangolin
spec:
  ports:
  - name: tcp-3000
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: tcp-3001
    port: 3001
    targetPort: 3001
    protocol: TCP
  - name: tcp-3002
    port: 3002
    targetPort: 3002
    protocol: TCP
  - name: tcp-3003
    port: 3003
    targetPort: 3003
    protocol: TCP
  selector:
    app: ${{ defaults.app_name }}-pangolin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}-pangolin
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-pangolin
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
  - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
    http:
      paths:
      - pathType: Prefix
        path: /api/v1
        backend:
          service:
            name: ${{ defaults.app_name }}-pangolin
            port:
              number: 3000
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ${{ defaults.app_name }}-pangolin
            port:
              number: 3002
  tls:
  - hosts:
    - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
    secretName: ${{ SEALOS_CERT_SECRET_NAME }}
---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/pangolin/logo.png
  name: Pangolin
  type: link
