apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: librechat
spec:
  title: 'LibreChat'
  url: 'https://librechat.ai/'
  gitRepo: 'https://github.com/danny-avila/LibreChat'
  author: 'Sealos'
  description: 'Enhanced ChatGPT Clone'
  locale: en
  readme: 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/librechat/README.md'
  icon: 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/librechat/logo.svg'
  screenshots:
    - 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/librechat/website-screenshot.webp'
  templateType: inline
  categories:
    - ai
  defaults:
    app_name:
      type: string
      value: librechat-${{ random(8) }}
    app_host:
      type: string
      value: librechat-${{ random(8) }}
    creds_iv:
      type: string
      value: ${{ random(32).toLowerCase().replace(/[^0-9a-f]/g, 'a') }}
    creds_key:
      type: string
      value: ${{ random(64).toLowerCase().replace(/[^0-9a-f]/g, 'a') }}
    jwt_refresh_secret:
      type: string
      value: ${{ random(64).toLowerCase().replace(/[^0-9a-f]/g, 'a') }}
    jwt_secret:
      type: string
      value: ${{ random(64).toLowerCase().replace(/[^0-9a-f]/g, 'a') }}
    meili_master_key:
      type: string
      value: ${{ random(32) }}
  inputs:
    OPENAI_REVERSE_PROXY:
      description: "reverse proxy for openai, remember to add /v1 to the end of the url"
      type: string
      default: "https://api.openai.com/v1"
      required: false

  i18n:
    zh:
      description: '增强型 ChatGPT 克隆应用，支持多模型聊天、搜索和会话管理。'
      readme: 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/librechat/README_zh.md'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-mongo
    app.kubernetes.io/instance: ${{ defaults.app_name }}-mongo
    app.kubernetes.io/managed-by: kbcli
  name: ${{ defaults.app_name }}-mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ghcr.io/danny-avila/librechat:v0.8.7
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: ghcr.io/danny-avila/librechat:v0.8.7
          env:
            - name: ALLOW_EMAIL_LOGIN
              value: "true"
            - name: ALLOW_REGISTRATION
              value: "true"
            - name: ALLOW_SOCIAL_LOGIN
              value: "false"
            - name: ALLOW_SOCIAL_REGISTRATION
              value: "false"
            - name: ANTHROPIC_API_KEY
              value: user_provided
            - name: ANTHROPIC_MODELS
              value: claude-1,claude-instant-1,claude-2
            - name: APP_TITLE
              value: LibreChat
            - name: AZURE_AI_SEARCH_API_KEY
              value: ""
            - name: AZURE_AI_SEARCH_API_VERSION
              value: ""
            - name: AZURE_AI_SEARCH_INDEX_NAME
              value: ""
            - name: AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE
              value: ""
            - name: AZURE_AI_SEARCH_SEARCH_OPTION_SELECT
              value: ""
            - name: AZURE_AI_SEARCH_SEARCH_OPTION_TOP
              value: ""
            - name: AZURE_AI_SEARCH_SERVICE_ENDPOINT
              value: ""
            - name: AZURE_OPENAI_MODELS
              value: gpt-3.5-turbo,gpt-4
            - name: AZURE_USE_MODEL_AS_DEPLOYMENT_NAME
              value: "TRUE"
            - name: BAN_DURATION
              value: 1000 * 60 * 60 * 2
            - name: BAN_INTERVAL
              value: "20"
            - name: BAN_VIOLATIONS
              value: "true"
            - name: BINGAI_TOKEN
              value: user_provided
            - name: CHATGPT_MODELS
              value: text-davinci-002-render-sha
            - name: CHATGPT_TOKEN
              value: ""
            - name: CHECK_BALANCE
              value: "false"
            - name: CONCURRENT_MESSAGE_MAX
              value: "2"
            - name: CONCURRENT_VIOLATION_SCORE
              value: "1"
            - name: CREDS_IV
              value: ${{ defaults.creds_iv }}
            - name: CREDS_KEY
              value: ${{ defaults.creds_key }}
            - name: DEBUG_CONSOLE
              value: "false"
            - name: DEBUG_LOGGING
              value: "true"
            - name: DEBUG_OPENAI
              value: "false"
            - name: DEBUG_PLUGINS
              value: "true"
            - name: DISCORD_CALLBACK_URL
              value: /oauth/discord/callback
            - name: DISCORD_CLIENT_ID
              value: ""
            - name: DISCORD_CLIENT_SECRET
              value: ""
            - name: DOMAIN_CLIENT
              value: http://localhost:3080
            - name: DOMAIN_SERVER
              value: http://localhost:3080
            - name: EMAIL_ALLOW_SELFSIGNED
              value: '         '
            - name: EMAIL_ENCRYPTION
              value: '               '
            - name: EMAIL_ENCRYPTION_HOSTNAME
              value: '      '
            - name: EMAIL_FROM
              value: noreply@librechat.ai
            - name: EMAIL_FROM_NAME
              value: '                '
            - name: EMAIL_PASSWORD
              value: '                 '
            - name: EMAIL_PORT
              value: '25                   '
            - name: EMAIL_USERNAME
              value: '                 '
            - name: FACEBOOK_CALLBACK_URL
              value: /oauth/facebook/callback
            - name: FACEBOOK_CLIENT_ID
              value: ""
            - name: FACEBOOK_CLIENT_SECRET
              value: ""
            - name: FIREBASE_API_KEY
              value: ""
            - name: FIREBASE_APP_ID
              value: ""
            - name: FIREBASE_AUTH_DOMAIN
              value: ""
            - name: FIREBASE_MESSAGING_SENDER_ID
              value: ""
            - name: FIREBASE_PROJECT_ID
              value: ""
            - name: FIREBASE_STORAGE_BUCKET
              value: ""
            - name: GITHUB_CALLBACK_URL
              value: /oauth/github/callback
            - name: GITHUB_CLIENT_ID
              value: ""
            - name: GITHUB_CLIENT_SECRET
              value: ""
            - name: GOOGLE_API_KEY
              value: ""
            - name: GOOGLE_CALLBACK_URL
              value: /oauth/google/callback
            - name: GOOGLE_CLIENT_ID
              value: ""
            - name: GOOGLE_CLIENT_SECRET
              value: ""
            - name: GOOGLE_CSE_ID
              value: ""
            - name: GOOGLE_KEY
              value: user_provided
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-mongo-mongodb-account-root
                  key: password
            - name: MONGO_URI
              value: >-
                mongodb://root:$(MONGO_PASSWORD)@${{ defaults.app_name }}-mongo-mongodb.${{ SEALOS_NAMESPACE }}.svc:27017/LibreChat?authSource=admin
            - name: HOST
              value: 0.0.0.0
            - name: MEILI_HOST
              value: http://${{ defaults.app_name }}-meilisearch:7700
            - name: OPENAI_REVERSE_PROXY
              value: ${{ inputs.OPENAI_REVERSE_PROXY }}
            - name: EMAIL_HOST
              value: ''
            - name: EMAIL_SERVICE
              value: ''
            - name: JWT_REFRESH_SECRET
              value: ${{ defaults.jwt_refresh_secret }}
            - name: JWT_SECRET
              value: ${{ defaults.jwt_secret }}
            - name: LIMIT_CONCURRENT_MESSAGES
              value: "true"
            - name: LIMIT_MESSAGE_IP
              value: "true"
            - name: LIMIT_MESSAGE_USER
              value: "false"
            - name: LOGIN_MAX
              value: "7"
            - name: LOGIN_VIOLATION_SCORE
              value: "1"
            - name: LOGIN_WINDOW
              value: "5"
            - name: MEILI_MASTER_KEY
              value: ${{ defaults.meili_master_key }}
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MESSAGE_IP_MAX
              value: "40"
            - name: MESSAGE_IP_WINDOW
              value: "1"
            - name: MESSAGE_USER_MAX
              value: "40"
            - name: MESSAGE_USER_WINDOW
              value: "1"
            - name: MESSAGE_VIOLATION_SCORE
              value: "1"
            - name: NO_INDEX
              value: "true"
            - name: NON_BROWSER_VIOLATION_SCORE
              value: "20"
            - name: OPENAI_API_KEY
              value: user_provided
            - name: OPENAI_MODERATION
              value: "false"
            - name: OPENAI_MODERATION_API_KEY
              value: ""
            - name: OPENID_BUTTON_LABEL
              value: ""
            - name: OPENID_CALLBACK_URL
              value: /oauth/openid/callback
            - name: OPENID_CLIENT_ID
              value: ""
            - name: OPENID_CLIENT_SECRET
              value: ""
            - name: OPENID_IMAGE_URL
              value: ""
            - name: OPENID_ISSUER
              value: ""
            - name: OPENID_SCOPE
              value: '"openid profile email"'
            - name: OPENID_SESSION_SECRET
              value: ""
            - name: PORT
              value: "3080"
            - name: PROXY
              value: ""
            - name: REFRESH_TOKEN_EXPIRY
              value: (1000 * 60 * 60 * 24) * 7
            - name: REGISTER_MAX
              value: "5"
            - name: REGISTER_WINDOW
              value: "60"
            - name: REGISTRATION_VIOLATION_SCORE
              value: "1"
            - name: SD_WEBUI_URL
              value: http://host.docker.internal:7860
            - name: SEARCH
              value: "true"
            - name: SERPAPI_API_KEY
              value: ""
            - name: SESSION_EXPIRY
              value: 1000 * 60 * 15
            - name: WOLFRAM_APP_ID
              value: ""
            - name: ZAPIER_NLA_API_KEY
              value: ""
          resources:
            requests:
              cpu: 20m
              memory: 51Mi
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 3080
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-appvn-clientvn-publicvn-images
              mountPath: /app/client/public/images
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /app/client/public/images
          value: '1'
        name: vn-appvn-clientvn-publicvn-images
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  ports:
    - name: http
      port: 3080
      targetPort: 3080
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}-meilisearch
  annotations:
    originImageName: getmeili/meilisearch:v1.5.0
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-meilisearch
    app: ${{ defaults.app_name }}-meilisearch
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}-meilisearch
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}-meilisearch
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}-meilisearch
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}-meilisearch
          image: getmeili/meilisearch:v1.5.0
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MEILI_MASTER_KEY
              value: ${{ defaults.meili_master_key }}
          resources:
            requests:
              cpu: 10m
              memory: 51Mi
            limits:
              cpu: 100m
              memory: 512Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 7700
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-meili-data
              mountPath: /meili_data
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /meili_data
          value: '1'
        name: vn-meili-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}-meilisearch
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}-meilisearch
    app: ${{ defaults.app_name }}-meilisearch
spec:
  ports:
    - name: http
      port: 7700
      targetPort: 7700
  selector:
    app: ${{ defaults.app_name }}-meilisearch

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 3080
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    kb.io/database: mongodb-8.0.4
    clusterdefinition.kubeblocks.io/name: mongodb
    app.kubernetes.io/instance: ${{ defaults.app_name }}-mongo
    helm.sh/chart: mongodb-cluster-0.9.1
    sealos-db-provider-cr: ${{ defaults.app_name }}-mongo
  name: ${{ defaults.app_name }}-mongo
  generation: 1
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys: []
  backup:
    enabled: true
    cronExpression: 0 18 * * *
    method: dump
    pitrEnabled: false
    retentionPeriod: 7d
  componentSpecs:
    - componentDef: mongodb
      serviceVersion: 8.0.4
      name: mongodb
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 51Mi
      serviceAccountName: ${{ defaults.app_name }}-mongo
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

  terminationPolicy: Delete
  tolerations: []

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-mongo
    app.kubernetes.io/instance: ${{ defaults.app_name }}-mongo
    app.kubernetes.io/managed-by: kbcli
  name: ${{ defaults.app_name }}-mongo
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-mongo
    app.kubernetes.io/instance: ${{ defaults.app_name }}-mongo
    app.kubernetes.io/managed-by: kbcli
  name: ${{ defaults.app_name }}-mongo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${{ defaults.app_name }}-mongo
subjects:
  - kind: ServiceAccount
    name: ${{ defaults.app_name }}-mongo

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/librechat/logo.svg"
  name: ${{ defaults.app_name }}
  type: link
