apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: node-red
spec:
  title: Node-RED
  url: https://nodered.org
  gitRepo: https://github.com/node-red/node-red
  author: Sealos
  description: Low-code programming for event-driven applications
  readme: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/node-red/README.md
  icon: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/node-red/logo.png
  templateType: inline
  locale: en
  i18n:
    zh:
      description: 面向事件驱动应用的低代码编程平台。
      readme: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/node-red/README_zh.md
  categories:
  - low-code
  defaults:
    app_host:
      type: string
      value: node-red-${{ random(8) }}
    app_name:
      type: string
      value: node-red-${{ random(8) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: nodered/node-red:4.1.6
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: ${{ defaults.app_name }}
        image: nodered/node-red:4.1.6
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 12Mi
        ports:
        - containerPort: 1880
        volumeMounts:
        - name: vn-data
          mountPath: /data
  serviceName: ${{ defaults.app_name }}
  volumeClaimTemplates:
  - metadata:
      name: vn-data
      annotations:
        path: /data
        value: '0.1'
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 0.1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    app: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
  - name: tcp-1880
    port: 1880
    targetPort: 1880
    protocol: TCP
  selector:
    app: ${{ defaults.app_name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: 'client_header_buffer_size 64k;

      large_client_header_buffers 4 128k;'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: "if ($request_uri ~* \\.(js|css|gif|jpe?g|png))\
      \ {\n  expires 30d;\n  add_header Cache-Control \"public\";\n}"
spec:
  rules:
  - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ${{ defaults.app_name }}
            port:
              number: 1880
  tls:
  - hosts:
    - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
    secretName: ${{ SEALOS_CERT_SECRET_NAME }}
---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/node-red/logo.png
  name: Node-RED
  type: link
