apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: photoprism
spec:
  title: 'PhotoPrism'
  url: 'https://www.photoprism.app/'
  gitRepo: 'https://github.com/photoprism/photoprism'
  author: 'Sealos'
  description: 'AI-Powered Photos App for the Decentralized Web.'
  readme: 'https://raw.githubusercontent.com/photoprism/photoprism/develop/README.md'
  icon: 'https://avatars.githubusercontent.com/u/32436079?s=48&v=4'
  templateType: inline
  categories:
    - tool
  defaults:
    app_host:
      # number or string..
      type: string
      value: photoprism-${{ random(8) }}
    app_name:
      type: string
      value: photoprism-${{ random(8) }}
  inputs:
    PHOTOPRISM_ADMIN_USER:
      description: "admin login username"
      type: string
      default: "admin"
      required: true
    PHOTOPRISM_ADMIN_PASSWORD:
      description: "initial admin password (8-72 characters)"
      type: string
      default: ""
      required: true

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: photoprism/photoprism:240711
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      automountServiceAccountToken: false
      containers:
        - name: ${{ defaults.app_name }}
          image: photoprism/photoprism:240711
          env:
            - name: PHOTOPRISM_ADMIN_USER
              value: ${{ inputs.PHOTOPRISM_ADMIN_USER }}
            - name: PHOTOPRISM_ADMIN_PASSWORD
              value: ${{ inputs.PHOTOPRISM_ADMIN_PASSWORD }}
            - name: PHOTOPRISM_AUTH_MODE
              value: password
            - name: PHOTOPRISM_SITE_URL
              value: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}/
            - name: PHOTOPRISM_DISABLE_TLS
              value: 'true'
            - name: PHOTOPRISM_DEFAULT_TLS
              value: 'false'
            - name: PHOTOPRISM_ORIGINALS_LIMIT
              value: '5000'
            - name: PHOTOPRISM_HTTP_COMPRESSION
              value: gzip
            - name: PHOTOPRISM_LOG_LEVEL
              value: info
            - name: PHOTOPRISM_READONLY
              value: 'false'
            - name: PHOTOPRISM_EXPERIMENTAL
              value: 'false'
            - name: PHOTOPRISM_DISABLE_CHOWN
              value: 'false'
            - name: PHOTOPRISM_DISABLE_WEBDAV
              value: 'false'
            - name: PHOTOPRISM_DISABLE_SETTINGS
              value: 'false'
            - name: PHOTOPRISM_DISABLE_TENSORFLOW
              value: 'false'
            - name: PHOTOPRISM_DISABLE_FACES
              value: 'false'
            - name: PHOTOPRISM_DISABLE_CLASSIFICATION
              value: 'false'
            - name: PHOTOPRISM_DISABLE_VECTORS
              value: 'false'
            - name: PHOTOPRISM_DISABLE_RAW
              value: 'false'
            - name: PHOTOPRISM_RAW_PRESETS
              value: 'false'
            - name: PHOTOPRISM_SIDECAR_YAML
              value: 'true'
            - name: PHOTOPRISM_BACKUP_ALBUMS
              value: 'true'
            - name: PHOTOPRISM_BACKUP_DATABASE
              value: 'true'
            - name: PHOTOPRISM_BACKUP_SCHEDULE
              value: daily
            - name: PHOTOPRISM_INDEX_SCHEDULE
              value: ''
            - name: PHOTOPRISM_AUTO_INDEX
              value: '300'
            - name: PHOTOPRISM_AUTO_IMPORT
              value: '-1'
            - name: PHOTOPRISM_DETECT_NSFW
              value: 'false'
            - name: PHOTOPRISM_UPLOAD_NSFW
              value: 'true'
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: sqlite
            - name: PHOTOPRISM_SITE_CAPTION
              value: AI-Powered Photos App
            - name: PHOTOPRISM_SITE_DESCRIPTION
              value: ''
            - name: PHOTOPRISM_SITE_AUTHOR
              value: ''
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1280Mi
          ports:
            - name: http
              protocol: TCP
              containerPort: 2342
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vn-photoprismvn-originals
              mountPath: /photoprism/originals
            - name: vn-photoprismvn-storage
              mountPath: /photoprism/storage
            - name: vn-photoprismvn-import
              mountPath: /photoprism/import
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /photoprism/originals
          value: '1'
        name: vn-photoprismvn-originals
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /photoprism/storage
          value: '1'
        name: vn-photoprismvn-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /photoprism/import
          value: '1'
        name: vn-photoprismvn-import
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 2342
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    higress.io/response-header-control-remove: X-Frame-Options
    higress.io/response-header-control-update: |
      Content-Security-Policy "default-src * blob: data: *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }}; img-src * data: blob: resource: *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }}; connect-src * wss: blob: resource:; style-src 'self' 'unsafe-inline' blob: *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }} resource:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }} resource: *.baidu.com *.bdstatic.com; frame-src 'self' *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }} mailto: tel: weixin: mtt: *.baidu.com; frame-ancestors 'self' https://${{ SEALOS_CLOUD_DOMAIN }} https://*.${{ SEALOS_CLOUD_DOMAIN }}"
      X-Xss-Protection "1; mode=block"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "X-Frame-Options:";
      more_set_headers "Content-Security-Policy: default-src * blob: data: *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }}; img-src * data: blob: resource: *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }}; connect-src * wss: blob: resource:; style-src 'self' 'unsafe-inline' blob: *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }} resource:; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }} resource: *.baidu.com *.bdstatic.com; frame-src 'self' *.${{ SEALOS_CLOUD_DOMAIN }} ${{ SEALOS_CLOUD_DOMAIN }} mailto: tel: weixin: mtt: *.baidu.com; frame-ancestors 'self' https://${{ SEALOS_CLOUD_DOMAIN }} https://*.${{ SEALOS_CLOUD_DOMAIN }}";
      more_set_headers "X-Xss-Protection: 1; mode=block";
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /()(.*)
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 2342
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://avatars.githubusercontent.com/u/32436079?s=48&v=4"
  name: PhotoPrism
  type: iframe