filebeat:
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: 7.17.28
    pullPolicy: IfNotPresent
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 500Mi
