apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: eaglercraft-server
spec:
  title: "EaglerCraft Server"
  url: "https://github.com/yangchuansheng/eaglercraft-server"
  gitRepo: "https://github.com/yangchuansheng/eaglercraft-server"
  author: "Sealos"
  description: "EaglerCraft 1.12.1 Minecraft server that runs in web browsers with WebSocket support"
  readme: "https://raw.githubusercontent.com/labring-actions/templates/main/template/eaglercraft-server/README.md"
  icon: "https://eaglercraft.com/img/favicon.ico"
  templateType: inline
  locale: en
  i18n:
    zh:
      title: "EaglerCraft 服务器"
      description: "可在网页浏览器中运行的 EaglerCraft 1.12.1 Minecraft 服务器，支持 WebSocket 连接"
  categories:
    - game
  defaults:
    app_host:
      type: string
      value: eaglercraft-${{ random(8) }}
    app_host_http:
      type: string
      value: eaglercraft-${{ random(8) }}
    app_name:
      type: string
      value: eaglercraft-${{ random(8) }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ghcr.io/yangchuansheng/eaglerx1.8server:1.12.1
    deploy.cloud.sealos.io/minReplicas: "1"
    deploy.cloud.sealos.io/maxReplicas: "1"
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      containers:
        - name: ${{ defaults.app_name }}
          image: ghcr.io/yangchuansheng/eaglerx1.8server:1.12.1
          imagePullPolicy: IfNotPresent
          env: []
          resources:
            requests:
              cpu: 50m
              memory: 102Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          ports:
            - containerPort: 5200
              name: websocket
            - containerPort: 5201
              name: http
          volumeMounts:
            - name: vn-eaglerx-1vn-8-servervn-servervn-world
              mountPath: /eaglerX-1.8-server/server/world/
            - name: vn-eaglerx-1vn-8-servervn-servervn-world-nether
              mountPath: /eaglerX-1.8-server/server/world_nether/
            - name: vn-eaglerx-1vn-8-servervn-servervn-world-the-end
              mountPath: /eaglerX-1.8-server/server/world_the_end/
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /eaglerX-1.8-server/server/world/
          value: "1"
        name: vn-eaglerx-1vn-8-servervn-servervn-world
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /eaglerX-1.8-server/server/world_nether/
          value: "1"
        name: vn-eaglerx-1vn-8-servervn-servervn-world-nether
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        annotations:
          path: /eaglerX-1.8-server/server/world_the_end/
          value: "1"
        name: vn-eaglerx-1vn-8-servervn-servervn-world-the-end
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 5200
      targetPort: 5200
      name: websocket
      protocol: TCP
    - port: 5201
      targetPort: 5201
      name: http
      protocol: TCP
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/backend-protocol: WS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 5200
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}-http
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host_http }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/backend-protocol: WS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: ${{ defaults.app_host_http }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 5201
  tls:
    - hosts:
        - ${{ defaults.app_host_http }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}
