# Template CR
apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: notifuse
  labels:
    cloud.sealos.io/app-deploy-manager: notifuse
spec:
  title: 'Notifuse - Transactional Email Platform'
  url: 'https://docs.notifuse.com/'
  gitRepo: 'https://github.com/notifuse/notifuse'
  author: 'Sealos'
  description: 'A transactional email platform with interactive Setup Wizard, SMTP relay support, and multi-workspace isolation'
  readme: 'https://raw.githubusercontent.com/labring-actions/templates/main/template/notifuse/README.md'
  icon: 'https://avatars.githubusercontent.com/u/12115165?s=48&v=4'
  templateType: inline
  locale: en
  i18n:
    zh:
      title: 'Notifuse - 事务邮件平台'
      description: '带交互式设置向导的事务邮件平台，支持 SMTP 中继和多工作空间隔离'
  categories:
    - backend
    - tool
  defaults:
    app_host:
      type: string
      value: notifuse-${{ random(8) }}
    app_name:
      type: string
      value: notifuse-${{ random(8) }}
    secret_key:
      type: string
      value: ${{ random(32) }}
    pg_password:
      type: string
      value: ${{ random(16) }}
  inputs:
    root_email:
      description: 'Root administrator email (e.g., admin@yourcompany.com)'
      type: string
      default: ''
      required: true
    smtp_host:
      description: 'SMTP server host (e.g., smtp.gmail.com)'
      type: string
      default: ''
      required: true
    smtp_port:
      description: 'SMTP server port (e.g., 587 or 465)'
      type: string
      default: '587'
      required: false
    smtp_username:
      description: 'SMTP username (e.g., noreply@yourcompany.com)'
      type: string
      default: ''
      required: true
    smtp_password:
      description: 'SMTP password'
      type: string
      default: ''
      required: true
    smtp_from_email:
      description: 'From email address (e.g., noreply@yourcompany.com)'
      type: string
      default: ''
      required: true
    smtp_from_name:
      description: 'From name (e.g., Your Company Name)'
      type: string
      default: ''
      required: false

---
# PostgreSQL ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli

---
# PostgreSQL Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
# PostgreSQL RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${{ defaults.app_name }}-pg
  labels:
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
    app.kubernetes.io/instance: ${{ defaults.app_name }}-pg
    app.kubernetes.io/managed-by: kbcli
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${{ defaults.app_name }}-pg
subjects:
  - kind: ServiceAccount
    name: ${{ defaults.app_name }}-pg

---
# PostgreSQL Cluster
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    clusterdefinition.kubeblocks.io/name: postgresql
    clusterversion.kubeblocks.io/name: postgresql-14.8.0
    sealos-db-provider-cr: ${{ defaults.app_name }}-pg
  annotations: {}
  name: ${{ defaults.app_name }}-pg
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys: []
  clusterDefinitionRef: postgresql
  clusterVersionRef: postgresql-14.8.0
  componentSpecs:
    - componentDefRef: postgresql
      monitor: true
      name: postgresql
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 51Mi
      serviceAccountName: ${{ defaults.app_name }}-pg
      switchPolicy:
        type: Noop
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  terminationPolicy: Delete
  tolerations: []

---
# Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: notifuse/notifuse:latest
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: wait-for-postgres
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: host
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: port
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: password
            - name: DB_NAME
              value: notifuse_system
          command:
            - /bin/sh
            - -c
            - |
              echo "waiting for postgresql to be ready..."
              until pg_isready -h ${PG_HOST} -p ${PG_PORT} -U ${PG_USERNAME}; do
                echo "postgresql not ready, rechecking in 2s"
                sleep 2
              done
              echo "database ${DB_NAME} is ready"
      containers:
        - name: ${{ defaults.app_name }}
          image: notifuse/notifuse:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # Required Variables
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${{ defaults.app_name }}-pg-conn-credential
                  key: password
            - name: SECRET_KEY
              value: ${{ defaults.secret_key }}
            # Application Variables (Optional with Setup Wizard)
            - name: ROOT_EMAIL
              value: ${{ inputs.root_email }}
            - name: API_ENDPOINT
              value: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
            - name: SMTP_HOST
              value: ${{ inputs.smtp_host }}
            - name: SMTP_PORT
              value: ${{ inputs.smtp_port }}
            - name: SMTP_USERNAME
              value: ${{ inputs.smtp_username }}
            - name: SMTP_PASSWORD
              value: ${{ inputs.smtp_password }}
            - name: SMTP_FROM_EMAIL
              value: ${{ inputs.smtp_from_email }}
            - name: SMTP_FROM_NAME
              value: ${{ inputs.smtp_from_name }}
          resources:
            limits:
              cpu: '200m'
              memory: 256Mi
            requests:
              cpu: '20m'
              memory: 25Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

---
# Application Service
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ${{ defaults.app_name }}
  type: ClusterIP

---
# Application Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8080
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
# App
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://avatars.githubusercontent.com/u/12115165?s=48&v=4"
  name: "Notifuse"
  type: link