apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: kitten-tts
spec:
  title: 'Kitten TTS'
  url: 'https://github.com/SamThinks-Com/Kitten-TTS-Server'
  gitRepo: 'https://github.com/SamThinks-Com/Kitten-TTS-Server'
  author: 'Sealos'
  description: 'Kitten-TTS-Server hosts the Kitten TTS model behind a small, fast API. It includes a built-in Web UI, audiobook-grade text handling, and GPU support. Use it for prototypes, research, or self-hosted TTS services.'
  readme: 'https://raw.githubusercontent.com/SamThinks-Com/Kitten-TTS-Server/refs/heads/main/README.md'
  icon: 'https://github.com/favicon.ico'
  templateType: inline
  locale: en
  i18n:
    zh:
      title: 'Kitten TTS'
      description: 'Kitten-TTS-Server 是一个文本转语音（TTS）服务，提供语音合成功能。'
  categories:
    - ai
    - tool
  defaults:
    app_name:
      type: string
      value: kitten-tts-${{ random(8) }}
    app_host:
      type: string
      value: kitten-tts-${{ random(8) }}
  inputs:
    hf_hub_enable_transfer:
      description: 'Enable faster Hugging Face downloads'
      type: boolean
      default: 'true'
      required: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ghcr.io/yangchuansheng/kitten-tts-server:cpu-v1.2
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  revisionHistoryLimit: 1
  replicas: 1
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: wait-for-db
          image: ghcr.io/yangchuansheng/kitten-tts-server:cpu-v1.2
          command:
            - /bin/sh
            - -c
            - |
              cp -rf /app/* /app-tmp/
          volumeMounts:
            - name: vn-app
              mountPath: /app-tmp
      containers:
        - name: ${{ defaults.app_name }}
          image: ghcr.io/yangchuansheng/kitten-tts-server:cpu-v1.2
          imagePullPolicy: IfNotPresent
          env:
            - name: HF_HUB_ENABLE_HF_TRANSFER
              value: "${{ inputs.hf_hub_enable_transfer === 'true' ? '1' : '0' }}"
          ports:
            - containerPort: 8005
              name: http
              protocol: TCP
          volumeMounts:
            - name: vn-app
              mountPath: /app
          resources:
            requests:
              cpu: 50m
              memory: 102Mi
            limits:
              cpu: 500m
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        annotations:
          path: /app
          value: '1'
        name: vn-app
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
      name: http
  selector:
    app: ${{ defaults.app_name }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 8005
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}

---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
  displayType: normal
  icon: "https://github.com/favicon.ico"
  name: "Kitten TTS"
  type: link