apiVersion: docker-to-sealos/v1
kind: TopologyEvidence
metadata:
  name: 7daystodie-topology
spec:
  appName: 7daystodie
  source: https://github.com/vinanrra/Docker-7DaysToDie/blob/01ef108e17482c735f5d5c922fa1a9d74617841e/docs/usage.md
  resources:
  - kind: StatefulSet
    name: ${{ defaults.app_name }}
    when: always
    replicas: 1
