apiVersion: docker-to-sealos/v1
kind: TopologyEvidence
metadata:
  name: eaglercraft-server-topology
spec:
  appName: eaglercraft-server
  source: https://github.com/labring-actions/templates/blob/ca5eecdb/template/eaglercraft-server/index.yaml
  resources:
    - kind: StatefulSet
      name: ${{ defaults.app_name }}
      when: always
      replicas: 1
