apiVersion: docker-to-sealos/v1
kind: TopologyEvidence
metadata:
  name: fxserver-topology
spec:
  appName: fxserver
  source: https://github.com/routmoute/fxserver/blob/75ad11c7a7b16b4ed3d95c0494152116e90a80b9/README.md#txadmin
  resources:
    - kind: StatefulSet
      name: ${{ defaults.app_name }}
      when: always
      replicas: 1
