apiVersion: docker-to-sealos/v1
kind: TopologyEvidence
metadata:
  name: localstack-topology
spec:
  appName: localstack
  source: https://github.com/localstack/localstack/blob/8b9a79f05846835cf4dff63ab7eefdde9df83783/docker-compose.yml
  resources:
    - kind: Deployment
      name: ${{ defaults.app_name }}
      when: always
      replicas: 1
