apiVersion: docker-to-sealos/v1
kind: TopologyEvidence
metadata:
  name: nakama-topology
spec:
  appName: nakama
  source: https://github.com/heroiclabs/nakama/blob/v3.40.0/docker-compose-postgres.yml
  resources:
    - kind: Cluster
      name: ${{ defaults.app_name }}-pg
      when: always
      components:
        - name: postgresql
          replicas: 1
    - kind: StatefulSet
      name: ${{ defaults.app_name }}
      when: always
      replicas: 1
