apiVersion: docker-to-sealos/v1
kind: TopologyEvidence
metadata:
  name: project-zomboid-topology
spec:
  appName: project-zomboid
  source: https://github.com/Danixu/project-zomboid-server-docker/blob/bdc90255ec920563ea993356b125e75c90bd2ecc/docker-compose.yml
  resources:
  - kind: StatefulSet
    name: ${{ defaults.app_name }}
    when: always
    replicas: 1
