apiVersion: docker-to-sealos/v1
kind: TopologyEvidence
metadata:
  name: signoz-topology
spec:
  appName: signoz
  source: https://raw.githubusercontent.com/SigNoz/signoz/v0.117.0/deploy/docker/docker-compose.yaml
  resources:
    - kind: StatefulSet
      name: ${{ defaults.app_name }}-zookeeper-0
      when: always
      replicas: 1
    - kind: StatefulSet
      name: ${{ defaults.app_name }}-clickhouse-0
      when: always
      replicas: 1
    - kind: StatefulSet
      name: ${{ defaults.app_name }}
      when: always
      replicas: 1
    - kind: Deployment
      name: ${{ defaults.app_name }}-otel-collector
      when: always
      replicas: 1
