apiVersion: docker-to-sealos/v1
kind: TopologyEvidence
metadata:
  name: tmodloader-topology
spec:
  appName: tmodloader
  source: https://github.com/JACOBSMILE/tmodloader1.4/blob/4e0d3069bee79bc549a591f7df9027ce3037e6d8/README.md#running-the-container
  resources:
    - kind: StatefulSet
      name: ${{ defaults.app_name }}
      when: always
      replicas: 1
