apiVersion: app.sealos.io/v1
kind: Template
metadata:
  name: localstack
spec:
  title: 'LocalStack'
  url: 'https://www.localstack.cloud/'
  gitRepo: 'https://github.com/localstack/localstack'
  author: 'LocalStack'
  description: 'Run an AWS-compatible local cloud emulator behind a public HTTPS gateway.'
  readme: 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/localstack/README.md'
  icon: 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/localstack/logo.svg'
  screenshots:
    - 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/localstack/website-screenshot.webp'
  templateType: inline
  locale: en
  i18n:
    zh:
      description: '运行兼容 AWS 的本地云模拟器，并通过公网 HTTPS 网关访问。'
      readme: 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/localstack/README_zh.md'
  categories:
    - dev-ops
    - tool
  defaults:
    app_name:
      type: string
      value: localstack-${{ random(8) }}
    app_host:
      type: string
      value: localstack-${{ random(8) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: localstack/localstack:4.14.0
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    app: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ${{ defaults.app_name }}
          image: localstack/localstack:4.14.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - mkdir -p /tmp/localstack-user && exec /usr/local/bin/docker-entrypoint.sh
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: DEBUG
              value: '0'
            - name: EXTERNAL_SERVICE_PORTS_START
              value: '4510'
            - name: EXTERNAL_SERVICE_PORTS_END
              value: '4560'
            - name: OVERRIDE_IN_DOCKER
              value: '1'
            - name: TEMP
              value: /tmp/localstack-user
            - name: DNS_ADDRESS
              value: '0'
            - name: LOCALSTACK_HOST
              value: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}:443
            - name: USE_SSL
              value: '1'
            - name: SQS_ENDPOINT_STRATEGY
              value: path
          ports:
            - name: edge
              containerPort: 4566
              protocol: TCP
            - name: ext-svc-4510
              containerPort: 4510
              protocol: TCP
            - name: ext-svc-4511
              containerPort: 4511
              protocol: TCP
            - name: ext-svc-4512
              containerPort: 4512
              protocol: TCP
            - name: ext-svc-4513
              containerPort: 4513
              protocol: TCP
            - name: ext-svc-4514
              containerPort: 4514
              protocol: TCP
            - name: ext-svc-4515
              containerPort: 4515
              protocol: TCP
            - name: ext-svc-4516
              containerPort: 4516
              protocol: TCP
            - name: ext-svc-4517
              containerPort: 4517
              protocol: TCP
            - name: ext-svc-4518
              containerPort: 4518
              protocol: TCP
            - name: ext-svc-4519
              containerPort: 4519
              protocol: TCP
            - name: ext-svc-4520
              containerPort: 4520
              protocol: TCP
            - name: ext-svc-4521
              containerPort: 4521
              protocol: TCP
            - name: ext-svc-4522
              containerPort: 4522
              protocol: TCP
            - name: ext-svc-4523
              containerPort: 4523
              protocol: TCP
            - name: ext-svc-4524
              containerPort: 4524
              protocol: TCP
            - name: ext-svc-4525
              containerPort: 4525
              protocol: TCP
            - name: ext-svc-4526
              containerPort: 4526
              protocol: TCP
            - name: ext-svc-4527
              containerPort: 4527
              protocol: TCP
            - name: ext-svc-4528
              containerPort: 4528
              protocol: TCP
            - name: ext-svc-4529
              containerPort: 4529
              protocol: TCP
            - name: ext-svc-4530
              containerPort: 4530
              protocol: TCP
            - name: ext-svc-4531
              containerPort: 4531
              protocol: TCP
            - name: ext-svc-4532
              containerPort: 4532
              protocol: TCP
            - name: ext-svc-4533
              containerPort: 4533
              protocol: TCP
            - name: ext-svc-4534
              containerPort: 4534
              protocol: TCP
            - name: ext-svc-4535
              containerPort: 4535
              protocol: TCP
            - name: ext-svc-4536
              containerPort: 4536
              protocol: TCP
            - name: ext-svc-4537
              containerPort: 4537
              protocol: TCP
            - name: ext-svc-4538
              containerPort: 4538
              protocol: TCP
            - name: ext-svc-4539
              containerPort: 4539
              protocol: TCP
            - name: ext-svc-4540
              containerPort: 4540
              protocol: TCP
            - name: ext-svc-4541
              containerPort: 4541
              protocol: TCP
            - name: ext-svc-4542
              containerPort: 4542
              protocol: TCP
            - name: ext-svc-4543
              containerPort: 4543
              protocol: TCP
            - name: ext-svc-4544
              containerPort: 4544
              protocol: TCP
            - name: ext-svc-4545
              containerPort: 4545
              protocol: TCP
            - name: ext-svc-4546
              containerPort: 4546
              protocol: TCP
            - name: ext-svc-4547
              containerPort: 4547
              protocol: TCP
            - name: ext-svc-4548
              containerPort: 4548
              protocol: TCP
            - name: ext-svc-4549
              containerPort: 4549
              protocol: TCP
            - name: ext-svc-4550
              containerPort: 4550
              protocol: TCP
            - name: ext-svc-4551
              containerPort: 4551
              protocol: TCP
            - name: ext-svc-4552
              containerPort: 4552
              protocol: TCP
            - name: ext-svc-4553
              containerPort: 4553
              protocol: TCP
            - name: ext-svc-4554
              containerPort: 4554
              protocol: TCP
            - name: ext-svc-4555
              containerPort: 4555
              protocol: TCP
            - name: ext-svc-4556
              containerPort: 4556
              protocol: TCP
            - name: ext-svc-4557
              containerPort: 4557
              protocol: TCP
            - name: ext-svc-4558
              containerPort: 4558
              protocol: TCP
            - name: ext-svc-4559
              containerPort: 4559
              protocol: TCP
          startupProbe:
            httpGet:
              path: /_localstack/health
              port: edge
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /_localstack/health
              port: edge
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: edge
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 25Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    app: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  selector:
    app: ${{ defaults.app_name }}
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
      protocol: TCP
    - name: ext-svc-4510
      port: 4510
      targetPort: 4510
      protocol: TCP
    - name: ext-svc-4511
      port: 4511
      targetPort: 4511
      protocol: TCP
    - name: ext-svc-4512
      port: 4512
      targetPort: 4512
      protocol: TCP
    - name: ext-svc-4513
      port: 4513
      targetPort: 4513
      protocol: TCP
    - name: ext-svc-4514
      port: 4514
      targetPort: 4514
      protocol: TCP
    - name: ext-svc-4515
      port: 4515
      targetPort: 4515
      protocol: TCP
    - name: ext-svc-4516
      port: 4516
      targetPort: 4516
      protocol: TCP
    - name: ext-svc-4517
      port: 4517
      targetPort: 4517
      protocol: TCP
    - name: ext-svc-4518
      port: 4518
      targetPort: 4518
      protocol: TCP
    - name: ext-svc-4519
      port: 4519
      targetPort: 4519
      protocol: TCP
    - name: ext-svc-4520
      port: 4520
      targetPort: 4520
      protocol: TCP
    - name: ext-svc-4521
      port: 4521
      targetPort: 4521
      protocol: TCP
    - name: ext-svc-4522
      port: 4522
      targetPort: 4522
      protocol: TCP
    - name: ext-svc-4523
      port: 4523
      targetPort: 4523
      protocol: TCP
    - name: ext-svc-4524
      port: 4524
      targetPort: 4524
      protocol: TCP
    - name: ext-svc-4525
      port: 4525
      targetPort: 4525
      protocol: TCP
    - name: ext-svc-4526
      port: 4526
      targetPort: 4526
      protocol: TCP
    - name: ext-svc-4527
      port: 4527
      targetPort: 4527
      protocol: TCP
    - name: ext-svc-4528
      port: 4528
      targetPort: 4528
      protocol: TCP
    - name: ext-svc-4529
      port: 4529
      targetPort: 4529
      protocol: TCP
    - name: ext-svc-4530
      port: 4530
      targetPort: 4530
      protocol: TCP
    - name: ext-svc-4531
      port: 4531
      targetPort: 4531
      protocol: TCP
    - name: ext-svc-4532
      port: 4532
      targetPort: 4532
      protocol: TCP
    - name: ext-svc-4533
      port: 4533
      targetPort: 4533
      protocol: TCP
    - name: ext-svc-4534
      port: 4534
      targetPort: 4534
      protocol: TCP
    - name: ext-svc-4535
      port: 4535
      targetPort: 4535
      protocol: TCP
    - name: ext-svc-4536
      port: 4536
      targetPort: 4536
      protocol: TCP
    - name: ext-svc-4537
      port: 4537
      targetPort: 4537
      protocol: TCP
    - name: ext-svc-4538
      port: 4538
      targetPort: 4538
      protocol: TCP
    - name: ext-svc-4539
      port: 4539
      targetPort: 4539
      protocol: TCP
    - name: ext-svc-4540
      port: 4540
      targetPort: 4540
      protocol: TCP
    - name: ext-svc-4541
      port: 4541
      targetPort: 4541
      protocol: TCP
    - name: ext-svc-4542
      port: 4542
      targetPort: 4542
      protocol: TCP
    - name: ext-svc-4543
      port: 4543
      targetPort: 4543
      protocol: TCP
    - name: ext-svc-4544
      port: 4544
      targetPort: 4544
      protocol: TCP
    - name: ext-svc-4545
      port: 4545
      targetPort: 4545
      protocol: TCP
    - name: ext-svc-4546
      port: 4546
      targetPort: 4546
      protocol: TCP
    - name: ext-svc-4547
      port: 4547
      targetPort: 4547
      protocol: TCP
    - name: ext-svc-4548
      port: 4548
      targetPort: 4548
      protocol: TCP
    - name: ext-svc-4549
      port: 4549
      targetPort: 4549
      protocol: TCP
    - name: ext-svc-4550
      port: 4550
      targetPort: 4550
      protocol: TCP
    - name: ext-svc-4551
      port: 4551
      targetPort: 4551
      protocol: TCP
    - name: ext-svc-4552
      port: 4552
      targetPort: 4552
      protocol: TCP
    - name: ext-svc-4553
      port: 4553
      targetPort: 4553
      protocol: TCP
    - name: ext-svc-4554
      port: 4554
      targetPort: 4554
      protocol: TCP
    - name: ext-svc-4555
      port: 4555
      targetPort: 4555
      protocol: TCP
    - name: ext-svc-4556
      port: 4556
      targetPort: 4556
      protocol: TCP
    - name: ext-svc-4557
      port: 4557
      targetPort: 4557
      protocol: TCP
    - name: ext-svc-4558
      port: 4558
      targetPort: 4558
      protocol: TCP
    - name: ext-svc-4559
      port: 4559
      targetPort: 4559
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ defaults.app_name }}
  labels:
    app: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    cloud.sealos.io/app-deploy-manager-domain: ${{ defaults.app_host }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 64k;
      large_client_header_buffers 4 128k;
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
spec:
  rules:
    - host: ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ${{ defaults.app_name }}
                port:
                  number: 4566
  tls:
    - hosts:
        - ${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}
      secretName: ${{ SEALOS_CERT_SECRET_NAME }}
---
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  data:
    url: https://${{ defaults.app_host }}.${{ SEALOS_CLOUD_DOMAIN }}/_localstack/health
  displayType: normal
  icon: 'https://raw.githubusercontent.com/labring-actions/templates/kb-0.9/template/localstack/logo.svg'
  name: 'LocalStack'
  type: link
