{{- if and .Values.sealos.app.enabled .Values.sealos.ingress.enabled .Values.zookeeper.config.adminServerEnabled }}
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: {{ include "zookeeper.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "zookeeper.name" . | quote }}
    cloud.sealos.io/app-deploy-manager: {{ include "zookeeper.name" . | quote }}
spec:
  data:
    url: https://{{ .Values.sealos.hostPrefix }}.{{ .Values.sealos.cloudDomain }}{{ .Values.sealos.app.entryPath }}
  displayType: normal
  icon: {{ .Values.sealos.app.icon | quote }}
  name: "Apache ZooKeeper Admin"
  type: link
{{- end }}
