apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.headlessName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "zookeeper.name" . | quote }}
    cloud.sealos.io/app-deploy-manager: {{ include "zookeeper.name" . | quote }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ include "zookeeper.name" . | quote }}
  ports:
    - name: client
      port: {{ .Values.zookeeper.service.clientPort }}
      targetPort: client
    - name: quorum
      port: {{ .Values.zookeeper.service.quorumPort }}
      targetPort: quorum
    - name: election
      port: {{ .Values.zookeeper.service.electionPort }}
      targetPort: election
