{{- if and .Values.sealos.app.enabled .Values.sealos.ingress.enabled }}
apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: {{ include "hadoop.resourceManagerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hadoop.resourceManagerName" . | quote }}
    cloud.sealos.io/app-deploy-manager: {{ include "hadoop.resourceManagerName" . | quote }}
spec:
  data:
    url: https://{{ .Values.sealos.resourceManager.hostPrefix }}.{{ .Values.sealos.cloudDomain }}{{ .Values.sealos.resourceManager.entryPath }}
  displayType: normal
  icon: {{ .Values.sealos.app.icon | quote }}
  name: "Apache Hadoop YARN"
  type: link
{{- end }}
