apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.resourceManagerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hadoop.resourceManagerName" . | quote }}
    cloud.sealos.io/app-deploy-manager: {{ include "hadoop.resourceManagerName" . | quote }}
spec:
  type: {{ .Values.hadoop.resourceManager.service.type }}
  selector:
    app: {{ include "hadoop.resourceManagerName" . | quote }}
  ports:
    - name: scheduler
      port: {{ .Values.hadoop.resourceManager.service.schedulerPort }}
      targetPort: scheduler
    - name: tracker
      port: {{ .Values.hadoop.resourceManager.service.resourceTrackerPort }}
      targetPort: tracker
    - name: client
      port: {{ .Values.hadoop.resourceManager.service.clientPort }}
      targetPort: client
    - name: admin
      port: {{ .Values.hadoop.resourceManager.service.adminPort }}
      targetPort: admin
    - name: http
      port: {{ .Values.hadoop.resourceManager.service.webPort }}
      targetPort: http
