apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.nodeManagerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "hadoop.nodeManagerName" . | quote }}
    cloud.sealos.io/app-deploy-manager: {{ include "hadoop.nodeManagerName" . | quote }}
spec:
  type: {{ .Values.hadoop.nodeManager.service.type }}
  selector:
    app: {{ include "hadoop.nodeManagerName" . | quote }}
  ports:
    - name: localizer
      port: {{ .Values.hadoop.nodeManager.service.localizerPort }}
      targetPort: localizer
    - name: nm
      port: {{ .Values.hadoop.nodeManager.service.nodeManagerPort }}
      targetPort: nm
    - name: http
      port: {{ .Values.hadoop.nodeManager.service.webPort }}
      targetPort: http
