logstash:
  image:
    repository: docker.elastic.co/logstash/logstash
    tag: 7.17.28
    pullPolicy: IfNotPresent
  replicas: 1
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 4Gi
  javaHeap: 1g
elasticsearch:
  caSecretName: elasticsearch-ca-secret
