apiVersion: v2
appVersion: v1.7.0
description: Helm chart of polardbx-operator
home: https://www.aliyun.com/product/drds
keywords:
- polardb-x
- operator
name: polardbx-operator
sources:
- https://github.com/ApsaraDB/galaxykube
type: application
version: 1.7.0
