apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app: "kibana"
spec:
  data:
    url: https://kibana.{{ .Values.sealos.cloudDomain }}/login
  displayType: normal
  icon: "https://raw.githubusercontent.com/elastic/elasticsearch/main/distribution/packages/rpm/src/main/resources/logo/elastic.gif"
  name: "Kibana"
  type: link
