apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: "kibana"
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/certs/tls.crt
    server.ssl.key: /usr/share/kibana/config/certs/tls.key

    elasticsearch.hosts: ["https://elasticsearch-master.{{ .Release.Namespace }}.svc:9200"]
    elasticsearch.username: elastic
    elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
    elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/elasticsearch-ca/tls.crt"]
    elasticsearch.ssl.verificationMode: full

    xpack.encryptedSavedObjects.encryptionKey: "0123456789abcdef0123456789abcdef"
    monitoring.ui.container.elasticsearch.enabled: true
