apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app: "kibana"
    cloud.sealos.io/app-deploy-manager-domain: kibana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
spec:
  tls:
    - hosts:
        - kibana.{{ .Values.sealos.cloudDomain }}
      secretName: {{ .Values.sealos.certSecretName }}
  rules:
    - host: kibana.{{ .Values.sealos.cloudDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601
