apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app: "kibana"
spec:
  type: ClusterIP
  selector:
    app: "kibana"
  ports:
    - name: https
      protocol: TCP
      port: 5601
      targetPort: 5601
