## Automatically sync to Coding after each commit through Github action
name: sync2coding
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:labring-actions/templates.git"
          destination-repo: "git@e.coding.net:g-vsop3980/labring-actions/templates.git"