apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-master-certs
  namespace: {{ .Release.Namespace }}
  labels:
    app: "elasticsearch-master"
    cloud.sealos.io/app-deploy-manager: elasticsearch-master
spec:
  secretName: {{ .Values.elasticsearch.tlsSecretName }}
  commonName: elasticsearch-master
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - elasticsearch-master
    - elasticsearch-master.{{ .Release.Namespace }}.svc
    - elasticsearch-master.{{ .Release.Namespace }}.svc.cluster.local
    - elasticsearch-master-headless
    - elasticsearch-master-headless.{{ .Release.Namespace }}.svc
    - elasticsearch-master-headless.{{ .Release.Namespace }}.svc.cluster.local
{{- range $i := until (int .Values.elasticsearch.replicas) }}
    - elasticsearch-master-{{ $i }}.elasticsearch-master-headless.{{ $.Release.Namespace }}.svc
    - elasticsearch-master-{{ $i }}.elasticsearch-master-headless.{{ $.Release.Namespace }}.svc.cluster.local
{{- end }}
  issuerRef:
    name: elasticsearch-ca-issuer
    kind: Issuer
