apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app: "elasticsearch-master"
    cloud.sealos.io/app-deploy-manager: elasticsearch-master
spec:
  isCA: true
  commonName: elasticsearch-ca
  secretName: elasticsearch-ca-secret
  duration: 87600h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: elasticsearch-selfsigned
    kind: Issuer
