apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: elasticsearch-selfsigned
  namespace: {{ .Release.Namespace }}
  labels:
    app: "elasticsearch-master"
    cloud.sealos.io/app-deploy-manager: elasticsearch-master
spec:
  selfSigned: {}
