apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    cloud.sealos.io/app-deploy-manager: elasticsearch-master
    app: "elasticsearch-master"
type: Opaque
stringData:
  username: elastic
  password: {{ .Values.elasticsearch.password | quote }}
