apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: {{ .Release.Namespace }}
  labels:
    cloud.sealos.io/app-deploy-manager: elasticsearch-master
    app: "elasticsearch-master"
spec:
  type: ClusterIP
  selector:
    app: "elasticsearch-master"
  publishNotReadyAddresses: false
  ports:
    - name: http
      protocol: TCP
      port: 9200
    - name: transport
      protocol: TCP
      port: 9300
