apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: "elasticsearch-master"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: "elasticsearch-master"
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
